// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as PlatformService from "./platformservice.js";
export {
    PlatformService
};

export {
    GameShortcutEntry,
    PlatformSettings,
    PlatformStartup,
    ResolvePlatformLaunchResult
} from "./models.js";
