// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AdminCheckResult {
    /**
     * Creates a new AdminCheckResult instance.
     * @param {Partial<AdminCheckResult>} [$$source = {}] - The source object to create the AdminCheckResult.
     */
    constructor($$source = {}) {
        if (!("needsAdmin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["needsAdmin"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["blocker"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AdminCheckResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AdminCheckResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AdminCheckResult(/** @type {Partial<AdminCheckResult>} */($$parsedSource));
    }
}

export class BackupResult {
    /**
     * Creates a new BackupResult instance.
     * @param {Partial<BackupResult>} [$$source = {}] - The source object to create the BackupResult.
     */
    constructor($$source = {}) {
        if (!("archivePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["archivePath"] = "";
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["files"] = 0;
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["restoredFrom"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackupResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupResult(/** @type {Partial<BackupResult>} */($$parsedSource));
    }
}

export class GameShortcutEntry {
    /**
     * Creates a new GameShortcutEntry instance.
     * @param {Partial<GameShortcutEntry>} [$$source = {}] - The source object to create the GameShortcutEntry.
     */
    constructor($$source = {}) {
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pinned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameShortcutEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GameShortcutEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameShortcutEntry(/** @type {Partial<GameShortcutEntry>} */($$parsedSource));
    }
}

export class PlatformSettings {
    /**
     * Creates a new PlatformSettings instance.
     * @param {Partial<PlatformSettings>} [$$source = {}] - The source object to create the PlatformSettings.
     */
    constructor($$source = {}) {
        if (!("RunAsAdmin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["RunAsAdmin"] = false;
        }
        if (!("TrayAccNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["TrayAccNumber"] = 0;
        }
        if (!("ForgetAccountEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ForgetAccountEnabled"] = false;
        }
        if (!("ClosingMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ClosingMethod"] = "";
        }
        if (!("StartingMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["StartingMethod"] = "";
        }
        if (!("AutoStart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AutoStart"] = false;
        }
        if (!("ShowShortNotes" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ShowShortNotes"] = false;
        }
        if (!("AccountNotes" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["AccountNotes"] = {};
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {GameShortcutEntry[] | undefined}
             */
            this["Shortcuts"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["AlwaysSwapOnShortcut"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["LaunchArguments"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlatformSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlatformSettings}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("AccountNotes" in $$parsedSource) {
            $$parsedSource["AccountNotes"] = $$createField7_0($$parsedSource["AccountNotes"]);
        }
        if ("Shortcuts" in $$parsedSource) {
            $$parsedSource["Shortcuts"] = $$createField8_0($$parsedSource["Shortcuts"]);
        }
        return new PlatformSettings(/** @type {Partial<PlatformSettings>} */($$parsedSource));
    }
}

export class PlatformStartup {
    /**
     * Creates a new PlatformStartup instance.
     * @param {Partial<PlatformStartup>} [$$source = {}] - The source object to create the PlatformStartup.
     */
    constructor($$source = {}) {
        if (!("homePlatformOrder" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["homePlatformOrder"] = [];
        }
        if (!("allPlatformNames" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["allPlatformNames"] = [];
        }
        if (!("disabledPlatformNames" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["disabledPlatformNames"] = [];
        }
        if (!("platformsFileMissing" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["platformsFileMissing"] = false;
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["theme"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * One-shot SPA route from CLI (e.g. open Steam page after elevated restart).
             * @member
             * @type {string | undefined}
             */
            this["cliNavigateHint"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlatformStartup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlatformStartup}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("homePlatformOrder" in $$parsedSource) {
            $$parsedSource["homePlatformOrder"] = $$createField0_0($$parsedSource["homePlatformOrder"]);
        }
        if ("allPlatformNames" in $$parsedSource) {
            $$parsedSource["allPlatformNames"] = $$createField1_0($$parsedSource["allPlatformNames"]);
        }
        if ("disabledPlatformNames" in $$parsedSource) {
            $$parsedSource["disabledPlatformNames"] = $$createField2_0($$parsedSource["disabledPlatformNames"]);
        }
        return new PlatformStartup(/** @type {Partial<PlatformStartup>} */($$parsedSource));
    }
}

export class ResolvePlatformLaunchResult {
    /**
     * Creates a new ResolvePlatformLaunchResult instance.
     * @param {Partial<ResolvePlatformLaunchResult>} [$$source = {}] - The source object to create the ResolvePlatformLaunchResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("needsManualLocate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["needsManualLocate"] = false;
        }
        if (!("foundViaShortcut" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["foundViaShortcut"] = false;
        }
        if (!("soughtExeName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["soughtExeName"] = "";
        }
        if (!("initialPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["initialPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolvePlatformLaunchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResolvePlatformLaunchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResolvePlatformLaunchResult(/** @type {Partial<ResolvePlatformLaunchResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = GameShortcutEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
