// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AdminCheckResult {
    "needsAdmin": boolean;
    "blocker"?: string;

    /** Creates a new AdminCheckResult instance. */
    constructor($$source: Partial<AdminCheckResult> = {}) {
        if (!("needsAdmin" in $$source)) {
            this["needsAdmin"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AdminCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AdminCheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AdminCheckResult($$parsedSource as Partial<AdminCheckResult>);
    }
}

export class BackupResult {
    "archivePath": string;
    "files": number;
    "bytes": number;
    "restoredFrom"?: string;

    /** Creates a new BackupResult instance. */
    constructor($$source: Partial<BackupResult> = {}) {
        if (!("archivePath" in $$source)) {
            this["archivePath"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupResult($$parsedSource as Partial<BackupResult>);
    }
}

export class GameShortcutEntry {
    "fileName": string;
    "pinned": boolean;

    /** Creates a new GameShortcutEntry instance. */
    constructor($$source: Partial<GameShortcutEntry> = {}) {
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameShortcutEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): GameShortcutEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameShortcutEntry($$parsedSource as Partial<GameShortcutEntry>);
    }
}

export class PlatformSettings {
    "RunAsAdmin": boolean;
    "TrayAccNumber": number;
    "ForgetAccountEnabled": boolean;
    "ClosingMethod": string;
    "StartingMethod": string;
    "AutoStart": boolean;
    "ShowShortNotes": boolean;
    "ShowLastUsed": boolean;
    "AccountNotes": { [_ in string]?: string };
    "Shortcuts"?: GameShortcutEntry[];
    "AlwaysSwapOnShortcut"?: boolean;
    "LaunchArguments"?: string;

    /** Creates a new PlatformSettings instance. */
    constructor($$source: Partial<PlatformSettings> = {}) {
        if (!("RunAsAdmin" in $$source)) {
            this["RunAsAdmin"] = false;
        }
        if (!("TrayAccNumber" in $$source)) {
            this["TrayAccNumber"] = 0;
        }
        if (!("ForgetAccountEnabled" in $$source)) {
            this["ForgetAccountEnabled"] = false;
        }
        if (!("ClosingMethod" in $$source)) {
            this["ClosingMethod"] = "";
        }
        if (!("StartingMethod" in $$source)) {
            this["StartingMethod"] = "";
        }
        if (!("AutoStart" in $$source)) {
            this["AutoStart"] = false;
        }
        if (!("ShowShortNotes" in $$source)) {
            this["ShowShortNotes"] = false;
        }
        if (!("ShowLastUsed" in $$source)) {
            this["ShowLastUsed"] = false;
        }
        if (!("AccountNotes" in $$source)) {
            this["AccountNotes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlatformSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): PlatformSettings {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("AccountNotes" in $$parsedSource) {
            $$parsedSource["AccountNotes"] = $$createField8_0($$parsedSource["AccountNotes"]);
        }
        if ("Shortcuts" in $$parsedSource) {
            $$parsedSource["Shortcuts"] = $$createField9_0($$parsedSource["Shortcuts"]);
        }
        return new PlatformSettings($$parsedSource as Partial<PlatformSettings>);
    }
}

export class PlatformStartup {
    "homePlatformOrder": string[];
    "allPlatformNames": string[];
    "disabledPlatformNames": string[];
    "platformsFileMissing": boolean;
    "language": string;
    "theme"?: string;

    /**
     * One-shot SPA route from CLI (e.g. open Steam page after elevated restart).
     */
    "cliNavigateHint"?: string;

    /** Creates a new PlatformStartup instance. */
    constructor($$source: Partial<PlatformStartup> = {}) {
        if (!("homePlatformOrder" in $$source)) {
            this["homePlatformOrder"] = [];
        }
        if (!("allPlatformNames" in $$source)) {
            this["allPlatformNames"] = [];
        }
        if (!("disabledPlatformNames" in $$source)) {
            this["disabledPlatformNames"] = [];
        }
        if (!("platformsFileMissing" in $$source)) {
            this["platformsFileMissing"] = false;
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlatformStartup instance from a string or object.
     */
    static createFrom($$source: any = {}): PlatformStartup {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("homePlatformOrder" in $$parsedSource) {
            $$parsedSource["homePlatformOrder"] = $$createField0_0($$parsedSource["homePlatformOrder"]);
        }
        if ("allPlatformNames" in $$parsedSource) {
            $$parsedSource["allPlatformNames"] = $$createField1_0($$parsedSource["allPlatformNames"]);
        }
        if ("disabledPlatformNames" in $$parsedSource) {
            $$parsedSource["disabledPlatformNames"] = $$createField2_0($$parsedSource["disabledPlatformNames"]);
        }
        return new PlatformStartup($$parsedSource as Partial<PlatformStartup>);
    }
}

export class ResolvePlatformLaunchResult {
    "ok": boolean;
    "needsManualLocate": boolean;
    "foundViaShortcut": boolean;
    "soughtExeName": string;
    "initialPath": string;

    /** Creates a new ResolvePlatformLaunchResult instance. */
    constructor($$source: Partial<ResolvePlatformLaunchResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("needsManualLocate" in $$source)) {
            this["needsManualLocate"] = false;
        }
        if (!("foundViaShortcut" in $$source)) {
            this["foundViaShortcut"] = false;
        }
        if (!("soughtExeName" in $$source)) {
            this["soughtExeName"] = "";
        }
        if (!("initialPath" in $$source)) {
            this["initialPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolvePlatformLaunchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ResolvePlatformLaunchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResolvePlatformLaunchResult($$parsedSource as Partial<ResolvePlatformLaunchResult>);
    }
}

/**
 * StatsPageRow is one page-visit aggregate in the stats report.
 */
export class StatsPageRow {
    "path": string;
    "visits": number;
    "totalTimeSec": number;

    /** Creates a new StatsPageRow instance. */
    constructor($$source: Partial<StatsPageRow> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("visits" in $$source)) {
            this["visits"] = 0;
        }
        if (!("totalTimeSec" in $$source)) {
            this["totalTimeSec"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatsPageRow instance from a string or object.
     */
    static createFrom($$source: any = {}): StatsPageRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatsPageRow($$parsedSource as Partial<StatsPageRow>);
    }
}

/**
 * StatsReport is returned to the SPA for the statistics modal.
 */
export class StatsReport {
    "shareEnabled": boolean;
    "osDisplay": string;
    "firstLaunch": string;
    "launchCount": number;
    "crashCount": number;
    "mostUsedPlatform": string;
    "totalTimeInAppSec": number;
    "totalSwitches": number;
    "totalGamesLaunched": number;
    "uniqueDaysSwitched": number;
    "uuid": string;
    "lastUpload": string;
    "switchers": StatsSwitcherRow[];
    "pages": StatsPageRow[];

    /** Creates a new StatsReport instance. */
    constructor($$source: Partial<StatsReport> = {}) {
        if (!("shareEnabled" in $$source)) {
            this["shareEnabled"] = false;
        }
        if (!("osDisplay" in $$source)) {
            this["osDisplay"] = "";
        }
        if (!("firstLaunch" in $$source)) {
            this["firstLaunch"] = "";
        }
        if (!("launchCount" in $$source)) {
            this["launchCount"] = 0;
        }
        if (!("crashCount" in $$source)) {
            this["crashCount"] = 0;
        }
        if (!("mostUsedPlatform" in $$source)) {
            this["mostUsedPlatform"] = "";
        }
        if (!("totalTimeInAppSec" in $$source)) {
            this["totalTimeInAppSec"] = 0;
        }
        if (!("totalSwitches" in $$source)) {
            this["totalSwitches"] = 0;
        }
        if (!("totalGamesLaunched" in $$source)) {
            this["totalGamesLaunched"] = 0;
        }
        if (!("uniqueDaysSwitched" in $$source)) {
            this["uniqueDaysSwitched"] = 0;
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("lastUpload" in $$source)) {
            this["lastUpload"] = "";
        }
        if (!("switchers" in $$source)) {
            this["switchers"] = [];
        }
        if (!("pages" in $$source)) {
            this["pages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatsReport instance from a string or object.
     */
    static createFrom($$source: any = {}): StatsReport {
        const $$createField12_0 = $$createType5;
        const $$createField13_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("switchers" in $$parsedSource) {
            $$parsedSource["switchers"] = $$createField12_0($$parsedSource["switchers"]);
        }
        if ("pages" in $$parsedSource) {
            $$parsedSource["pages"] = $$createField13_0($$parsedSource["pages"]);
        }
        return new StatsReport($$parsedSource as Partial<StatsReport>);
    }
}

/**
 * StatsSwitcherRow is one platform block in the stats report (bindings / UI).
 */
export class StatsSwitcherRow {
    "platform": string;
    "accounts": number;
    "switches": number;
    "uniqueDays": number;
    "gameShortcuts": number;
    "gameShortcutsHotbar": number;
    "gamesLaunched": number;
    "firstActive": string;
    "lastActive": string;

    /** Creates a new StatsSwitcherRow instance. */
    constructor($$source: Partial<StatsSwitcherRow> = {}) {
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("accounts" in $$source)) {
            this["accounts"] = 0;
        }
        if (!("switches" in $$source)) {
            this["switches"] = 0;
        }
        if (!("uniqueDays" in $$source)) {
            this["uniqueDays"] = 0;
        }
        if (!("gameShortcuts" in $$source)) {
            this["gameShortcuts"] = 0;
        }
        if (!("gameShortcutsHotbar" in $$source)) {
            this["gameShortcutsHotbar"] = 0;
        }
        if (!("gamesLaunched" in $$source)) {
            this["gamesLaunched"] = 0;
        }
        if (!("firstActive" in $$source)) {
            this["firstActive"] = "";
        }
        if (!("lastActive" in $$source)) {
            this["lastActive"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatsSwitcherRow instance from a string or object.
     */
    static createFrom($$source: any = {}): StatsSwitcherRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatsSwitcherRow($$parsedSource as Partial<StatsSwitcherRow>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = GameShortcutEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = StatsSwitcherRow.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = StatsPageRow.createFrom;
const $$createType7 = $Create.Array($$createType6);
