// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * GameShortcutEntry is one cached game shortcut (.lnk / .url) in the footer bar or dropdown.
 */
export class GameShortcutEntry {
    "fileName": string;
    "pinned": boolean;

    /** Creates a new GameShortcutEntry instance. */
    constructor($$source: Partial<GameShortcutEntry> = {}) {
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameShortcutEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): GameShortcutEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameShortcutEntry($$parsedSource as Partial<GameShortcutEntry>);
    }
}

/**
 * PlatformSettings are shared per-platform fields stored in Settings/<Name>Settings.json
 * (Steam uses SteamSettings.json alongside Steam-specific keys in the same file).
 */
export class PlatformSettings {
    "RunAsAdmin": boolean;
    "TrayAccNumber": number;
    "ForgetAccountEnabled": boolean;
    "ClosingMethod": string;
    "StartingMethod": string;
    "AutoStart": boolean;
    "ShowShortNotes": boolean;
    "AccountNotes": { [_ in string]?: string };
    "Shortcuts"?: GameShortcutEntry[];
    "AlwaysSwapOnShortcut"?: boolean;

    /** Creates a new PlatformSettings instance. */
    constructor($$source: Partial<PlatformSettings> = {}) {
        if (!("RunAsAdmin" in $$source)) {
            this["RunAsAdmin"] = false;
        }
        if (!("TrayAccNumber" in $$source)) {
            this["TrayAccNumber"] = 0;
        }
        if (!("ForgetAccountEnabled" in $$source)) {
            this["ForgetAccountEnabled"] = false;
        }
        if (!("ClosingMethod" in $$source)) {
            this["ClosingMethod"] = "";
        }
        if (!("StartingMethod" in $$source)) {
            this["StartingMethod"] = "";
        }
        if (!("AutoStart" in $$source)) {
            this["AutoStart"] = false;
        }
        if (!("ShowShortNotes" in $$source)) {
            this["ShowShortNotes"] = false;
        }
        if (!("AccountNotes" in $$source)) {
            this["AccountNotes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlatformSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): PlatformSettings {
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("AccountNotes" in $$parsedSource) {
            $$parsedSource["AccountNotes"] = $$createField7_0($$parsedSource["AccountNotes"]);
        }
        if ("Shortcuts" in $$parsedSource) {
            $$parsedSource["Shortcuts"] = $$createField8_0($$parsedSource["Shortcuts"]);
        }
        return new PlatformSettings($$parsedSource as Partial<PlatformSettings>);
    }
}

/**
 * PlatformStartup is the initial payload for the homepage and manage-platforms views.
 */
export class PlatformStartup {
    "homePlatformOrder": string[];
    "allPlatformNames": string[];
    "disabledPlatformNames": string[];
    "platformsFileMissing": boolean;
    "language": string;

    /**
     * CliNavigateHint is a one-shot JSON route from a prior ProcessCommand line (e.g. "Steam" to open that page).
     */
    "cliNavigateHint"?: string;

    /** Creates a new PlatformStartup instance. */
    constructor($$source: Partial<PlatformStartup> = {}) {
        if (!("homePlatformOrder" in $$source)) {
            this["homePlatformOrder"] = [];
        }
        if (!("allPlatformNames" in $$source)) {
            this["allPlatformNames"] = [];
        }
        if (!("disabledPlatformNames" in $$source)) {
            this["disabledPlatformNames"] = [];
        }
        if (!("platformsFileMissing" in $$source)) {
            this["platformsFileMissing"] = false;
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlatformStartup instance from a string or object.
     */
    static createFrom($$source: any = {}): PlatformStartup {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("homePlatformOrder" in $$parsedSource) {
            $$parsedSource["homePlatformOrder"] = $$createField0_0($$parsedSource["homePlatformOrder"]);
        }
        if ("allPlatformNames" in $$parsedSource) {
            $$parsedSource["allPlatformNames"] = $$createField1_0($$parsedSource["allPlatformNames"]);
        }
        if ("disabledPlatformNames" in $$parsedSource) {
            $$parsedSource["disabledPlatformNames"] = $$createField2_0($$parsedSource["disabledPlatformNames"]);
        }
        return new PlatformStartup($$parsedSource as Partial<PlatformStartup>);
    }
}

/**
 * ResolvePlatformLaunchResult is returned before navigating to a platform page.
 */
export class ResolvePlatformLaunchResult {
    "ok": boolean;
    "needsManualLocate": boolean;
    "foundViaShortcut": boolean;
    "soughtExeName": string;
    "initialPath": string;

    /** Creates a new ResolvePlatformLaunchResult instance. */
    constructor($$source: Partial<ResolvePlatformLaunchResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("needsManualLocate" in $$source)) {
            this["needsManualLocate"] = false;
        }
        if (!("foundViaShortcut" in $$source)) {
            this["foundViaShortcut"] = false;
        }
        if (!("soughtExeName" in $$source)) {
            this["soughtExeName"] = "";
        }
        if (!("initialPath" in $$source)) {
            this["initialPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolvePlatformLaunchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ResolvePlatformLaunchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResolvePlatformLaunchResult($$parsedSource as Partial<ResolvePlatformLaunchResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = GameShortcutEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
