// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PlatformSettings are shared per-platform fields stored in Settings/<Name>Settings.json
 * (Steam uses SteamSettings.json alongside Steam-specific keys in the same file).
 */
export class PlatformSettings {
    /**
     * Creates a new PlatformSettings instance.
     * @param {Partial<PlatformSettings>} [$$source = {}] - The source object to create the PlatformSettings.
     */
    constructor($$source = {}) {
        if (!("RunAsAdmin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["RunAsAdmin"] = false;
        }
        if (!("TrayAccNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["TrayAccNumber"] = 0;
        }
        if (!("ForgetAccountEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ForgetAccountEnabled"] = false;
        }
        if (!("ClosingMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ClosingMethod"] = "";
        }
        if (!("StartingMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["StartingMethod"] = "";
        }
        if (!("AutoStart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AutoStart"] = false;
        }
        if (!("ShowShortNotes" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ShowShortNotes"] = false;
        }
        if (!("AccountNotes" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["AccountNotes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlatformSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlatformSettings}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("AccountNotes" in $$parsedSource) {
            $$parsedSource["AccountNotes"] = $$createField7_0($$parsedSource["AccountNotes"]);
        }
        return new PlatformSettings(/** @type {Partial<PlatformSettings>} */($$parsedSource));
    }
}

/**
 * PlatformStartup is the initial payload for the homepage and manage-platforms views.
 */
export class PlatformStartup {
    /**
     * Creates a new PlatformStartup instance.
     * @param {Partial<PlatformStartup>} [$$source = {}] - The source object to create the PlatformStartup.
     */
    constructor($$source = {}) {
        if (!("homePlatformOrder" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["homePlatformOrder"] = [];
        }
        if (!("allPlatformNames" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["allPlatformNames"] = [];
        }
        if (!("disabledPlatformNames" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["disabledPlatformNames"] = [];
        }
        if (!("platformsFileMissing" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["platformsFileMissing"] = false;
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlatformStartup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlatformStartup}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("homePlatformOrder" in $$parsedSource) {
            $$parsedSource["homePlatformOrder"] = $$createField0_0($$parsedSource["homePlatformOrder"]);
        }
        if ("allPlatformNames" in $$parsedSource) {
            $$parsedSource["allPlatformNames"] = $$createField1_0($$parsedSource["allPlatformNames"]);
        }
        if ("disabledPlatformNames" in $$parsedSource) {
            $$parsedSource["disabledPlatformNames"] = $$createField2_0($$parsedSource["disabledPlatformNames"]);
        }
        return new PlatformStartup(/** @type {Partial<PlatformStartup>} */($$parsedSource));
    }
}

/**
 * ResolvePlatformLaunchResult is returned before navigating to a platform page.
 */
export class ResolvePlatformLaunchResult {
    /**
     * Creates a new ResolvePlatformLaunchResult instance.
     * @param {Partial<ResolvePlatformLaunchResult>} [$$source = {}] - The source object to create the ResolvePlatformLaunchResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("needsManualLocate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["needsManualLocate"] = false;
        }
        if (!("foundViaShortcut" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["foundViaShortcut"] = false;
        }
        if (!("soughtExeName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["soughtExeName"] = "";
        }
        if (!("initialPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["initialPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolvePlatformLaunchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResolvePlatformLaunchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResolvePlatformLaunchResult(/** @type {Partial<ResolvePlatformLaunchResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
