// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlatformService exposes platform list, settings, and launch resolution to the UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyPlatformsJSONFile(sourcePath: string): $CancellablePromise<void> {
    return $Call.ByID(2231300943, sourcePath);
}

/**
 * ConfirmPlatformExePath validates basename and saves the full path to settings.
 */
export function ConfirmPlatformExePath(platformKey: string, exeFullPath: string): $CancellablePromise<void> {
    return $Call.ByID(3388066149, platformKey, exeFullPath);
}

export function GetLanguage(): $CancellablePromise<string> {
    return $Call.ByID(1329797675);
}

/**
 * GetPlatformExeIcon returns a public URL under /img/shortcuts/... for the platform exe icon, or "" on failure.
 */
export function GetPlatformExeIcon(platformKey: string): $CancellablePromise<string> {
    return $Call.ByID(3242817395, platformKey);
}

/**
 * GetPlatformInstallFolder returns the directory containing the platform's primary executable, if known.
 */
export function GetPlatformInstallFolder(platformKey: string): $CancellablePromise<string> {
    return $Call.ByID(3951430321, platformKey);
}

/**
 * GetPlatformSettings returns shared per-platform settings from Settings/<Platform>Settings.json
 * (Steam: SteamSettings.json, unmarshalling only common keys).
 */
export function GetPlatformSettings(platformKey: string): $CancellablePromise<$models.PlatformSettings> {
    return $Call.ByID(1698365991, platformKey).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetStartup(): $CancellablePromise<$models.PlatformStartup> {
    return $Call.ByID(133724378).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * LaunchPlatform starts the platform executable (no account switch).
 */
export function LaunchPlatform(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(1880641703, platformKey);
}

/**
 * OpenPlatformFolder opens the install folder in the native file manager.
 */
export function OpenPlatformFolder(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(3725594492, platformKey);
}

/**
 * PickPlatformsJSON opens a native file dialog. Returns ("", nil) if the user cancels.
 */
export function PickPlatformsJSON(): $CancellablePromise<string> {
    return $Call.ByID(2979264020);
}

/**
 * ResetPlatformSettings resets the current platform's settings file to defaults.
 */
export function ResetPlatformSettings(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(232845660, platformKey);
}

/**
 * ResolvePlatformExeFullPath returns the absolute path to the platform's primary executable, if known.
 */
export function ResolvePlatformExeFullPath(platformKey: string): $CancellablePromise<string> {
    return $Call.ByID(986665928, platformKey);
}

/**
 * ResolvePlatformLaunch checks saved path, default exe path, then OS-specific shortcut discovery.
 */
export function ResolvePlatformLaunch(platformKey: string): $CancellablePromise<$models.ResolvePlatformLaunchResult> {
    return $Call.ByID(176484757, platformKey).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RestoreDefaultPlatformsJSON(): $CancellablePromise<void> {
    return $Call.ByID(1760795478);
}

export function SaveHomeOrder(order: string[]): $CancellablePromise<void> {
    return $Call.ByID(1124685899, order);
}

/**
 * SavePlatformSettings merges shared fields into the per-platform JSON without removing other keys.
 */
export function SavePlatformSettings(platformKey: string, s: $models.PlatformSettings): $CancellablePromise<void> {
    return $Call.ByID(2552014136, platformKey, s);
}

/**
 * SetActionBarStatus is bound for the UI and other Go callers that go through services.
 */
export function SetActionBarStatus(text: string): $CancellablePromise<void> {
    return $Call.ByID(85095566, text);
}

export function SetDisabledPlatforms(disabled: string[]): $CancellablePromise<void> {
    return $Call.ByID(3278316535, disabled);
}

export function SetLanguage(code: string): $CancellablePromise<void> {
    return $Call.ByID(1843532479, code);
}

export function SetPlatformExePath(platformKey: string, exePath: string): $CancellablePromise<void> {
    return $Call.ByID(2853813257, platformKey, exePath);
}

// Private type creation functions
const $$createType0 = $models.PlatformSettings.createFrom;
const $$createType1 = $models.PlatformStartup.createFrom;
const $$createType2 = $models.ResolvePlatformLaunchResult.createFrom;
