// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlatformService exposes platform list, settings, and launch resolution to the UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} sourcePath
 * @returns {$CancellablePromise<void>}
 */
export function ApplyPlatformsJSONFile(sourcePath) {
    return $Call.ByID(2231300943, sourcePath);
}

/**
 * ConfirmPlatformExePath validates basename and saves the full path to settings.
 * @param {string} platformKey
 * @param {string} exeFullPath
 * @returns {$CancellablePromise<void>}
 */
export function ConfirmPlatformExePath(platformKey, exeFullPath) {
    return $Call.ByID(3388066149, platformKey, exeFullPath);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetLanguage() {
    return $Call.ByID(1329797675);
}

/**
 * GetPlatformInstallFolder returns the directory containing the platform's primary executable, if known.
 * @param {string} platformKey
 * @returns {$CancellablePromise<string>}
 */
export function GetPlatformInstallFolder(platformKey) {
    return $Call.ByID(3951430321, platformKey);
}

/**
 * GetPlatformSettings returns shared per-platform settings from Settings/<Platform>Settings.json
 * (Steam: SteamSettings.json, unmarshalling only common keys).
 * @param {string} platformKey
 * @returns {$CancellablePromise<$models.PlatformSettings>}
 */
export function GetPlatformSettings(platformKey) {
    return $Call.ByID(1698365991, platformKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.PlatformStartup>}
 */
export function GetStartup() {
    return $Call.ByID(133724378).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * OpenPlatformFolder opens the install folder in the native file manager.
 * @param {string} platformKey
 * @returns {$CancellablePromise<void>}
 */
export function OpenPlatformFolder(platformKey) {
    return $Call.ByID(3725594492, platformKey);
}

/**
 * PickPlatformsJSON opens a native file dialog. Returns ("", nil) if the user cancels.
 * @returns {$CancellablePromise<string>}
 */
export function PickPlatformsJSON() {
    return $Call.ByID(2979264020);
}

/**
 * ResetPlatformSettings resets the current platform's settings file to defaults.
 * @param {string} platformKey
 * @returns {$CancellablePromise<void>}
 */
export function ResetPlatformSettings(platformKey) {
    return $Call.ByID(232845660, platformKey);
}

/**
 * ResolvePlatformLaunch checks saved path, default exe path, then OS-specific shortcut discovery.
 * @param {string} platformKey
 * @returns {$CancellablePromise<$models.ResolvePlatformLaunchResult>}
 */
export function ResolvePlatformLaunch(platformKey) {
    return $Call.ByID(176484757, platformKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RestoreDefaultPlatformsJSON() {
    return $Call.ByID(1760795478);
}

/**
 * @param {string[]} order
 * @returns {$CancellablePromise<void>}
 */
export function SaveHomeOrder(order) {
    return $Call.ByID(1124685899, order);
}

/**
 * SavePlatformSettings merges shared fields into the per-platform JSON without removing other keys.
 * @param {string} platformKey
 * @param {$models.PlatformSettings} s
 * @returns {$CancellablePromise<void>}
 */
export function SavePlatformSettings(platformKey, s) {
    return $Call.ByID(2552014136, platformKey, s);
}

/**
 * SetActionBarStatus is bound for the UI and other Go callers that go through services.
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function SetActionBarStatus(text) {
    return $Call.ByID(85095566, text);
}

/**
 * @param {string[]} disabled
 * @returns {$CancellablePromise<void>}
 */
export function SetDisabledPlatforms(disabled) {
    return $Call.ByID(3278316535, disabled);
}

/**
 * @param {string} code
 * @returns {$CancellablePromise<void>}
 */
export function SetLanguage(code) {
    return $Call.ByID(1843532479, code);
}

/**
 * @param {string} platformKey
 * @param {string} exePath
 * @returns {$CancellablePromise<void>}
 */
export function SetPlatformExePath(platformKey, exePath) {
    return $Call.ByID(2853813257, platformKey, exePath);
}

// Private type creation functions
const $$createType0 = $models.PlatformSettings.createFrom;
const $$createType1 = $models.PlatformStartup.createFrom;
const $$createType2 = $models.ResolvePlatformLaunchResult.createFrom;
