// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyPlatformsJSONFile(sourcePath: string): $CancellablePromise<void> {
    return $Call.ByID(2231300943, sourcePath);
}

export function BackupPlatform(platformKey: string, everything: boolean): $CancellablePromise<$models.BackupResult> {
    return $Call.ByID(2310227406, platformKey, everything).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CheckAdminForPlatform(platformKey: string): $CancellablePromise<$models.AdminCheckResult> {
    return $Call.ByID(1142940076, platformKey).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ClearPlatformCache(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(4269705643, platformKey);
}

export function ConfirmPlatformExePath(platformKey: string, exeFullPath: string): $CancellablePromise<void> {
    return $Call.ByID(3388066149, platformKey, exeFullPath);
}

export function GetDesktopHomeShortcutExists(): $CancellablePromise<boolean> {
    return $Call.ByID(1436342586);
}

export function GetExitToTray(): $CancellablePromise<boolean> {
    return $Call.ByID(3705594180);
}

export function GetLanguage(): $CancellablePromise<string> {
    return $Call.ByID(1329797675);
}

export function GetMinimizeOnSwitch(): $CancellablePromise<boolean> {
    return $Call.ByID(2562015012);
}

export function GetOfflineMode(): $CancellablePromise<boolean> {
    return $Call.ByID(125846475);
}

export function GetPlatformExeIcon(platformKey: string): $CancellablePromise<string> {
    return $Call.ByID(3242817395, platformKey);
}

export function GetPlatformInstallFolder(platformKey: string): $CancellablePromise<string> {
    return $Call.ByID(3951430321, platformKey);
}

export function GetPlatformSettings(platformKey: string): $CancellablePromise<$models.PlatformSettings> {
    return $Call.ByID(1698365991, platformKey).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetProtocolEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(3867357470);
}

export function GetStartProgramCentered(): $CancellablePromise<boolean> {
    return $Call.ByID(2764521137);
}

export function GetStartTrayWithWindows(): $CancellablePromise<boolean> {
    return $Call.ByID(2723837104);
}

export function GetStartup(): $CancellablePromise<$models.PlatformStartup> {
    return $Call.ByID(133724378).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetTheme(): $CancellablePromise<string> {
    return $Call.ByID(3289970754);
}

export function HasPlatformBackupFolders(platformKey: string): $CancellablePromise<boolean> {
    return $Call.ByID(2360319221, platformKey);
}

export function HasPlatformCachePaths(platformKey: string): $CancellablePromise<boolean> {
    return $Call.ByID(2913727920, platformKey);
}

export function HasShortcutMainExe(platformKey: string): $CancellablePromise<boolean> {
    return $Call.ByID(340062970, platformKey);
}

export function LaunchPlatform(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(1880641703, platformKey);
}

export function LaunchPlatformAs(platformKey: string, admin: boolean): $CancellablePromise<void> {
    return $Call.ByID(2773698227, platformKey, admin);
}

export function OpenPlatformBackupFolder(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(1776189318, platformKey);
}

export function OpenPlatformFolder(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(3725594492, platformKey);
}

export function PickPlatformsJSON(): $CancellablePromise<string> {
    return $Call.ByID(2979264020);
}

export function ResetPlatformSettings(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(232845660, platformKey);
}

export function ResolvePlatformExeFullPath(platformKey: string): $CancellablePromise<string> {
    return $Call.ByID(986665928, platformKey);
}

export function ResolvePlatformLaunch(platformKey: string): $CancellablePromise<$models.ResolvePlatformLaunchResult> {
    return $Call.ByID(176484757, platformKey).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * RestartAsAdmin re-execs elevated with args and exits; main should register winutil.RegisterSingletonReleaser first.
 */
export function RestartAsAdmin(args: string[]): $CancellablePromise<void> {
    return $Call.ByID(2717041837, args);
}

export function RestoreDefaultPlatformsJSON(): $CancellablePromise<void> {
    return $Call.ByID(1760795478);
}

export function RestoreLatestPlatformBackup(platformKey: string): $CancellablePromise<$models.BackupResult> {
    return $Call.ByID(2230632465, platformKey).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveHomeOrder(order: string[]): $CancellablePromise<void> {
    return $Call.ByID(1124685899, order);
}

export function SavePlatformSettings(platformKey: string, s: $models.PlatformSettings): $CancellablePromise<void> {
    return $Call.ByID(2552014136, platformKey, s);
}

/**
 * SetActionBarStatus is bound for the UI and other Go callers that go through services.
 */
export function SetActionBarStatus(text: string): $CancellablePromise<void> {
    return $Call.ByID(85095566, text);
}

export function SetDesktopHomeShortcut(create: boolean): $CancellablePromise<void> {
    return $Call.ByID(3719931318, create);
}

export function SetDisabledPlatforms(disabled: string[]): $CancellablePromise<void> {
    return $Call.ByID(3278316535, disabled);
}

export function SetExitToTray(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(4055135808, enabled);
}

export function SetLanguage(code: string): $CancellablePromise<void> {
    return $Call.ByID(1843532479, code);
}

export function SetMinimizeOnSwitch(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1588199976, enabled);
}

export function SetOfflineMode(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(821998887, enabled);
}

export function SetPlatformExePath(platformKey: string, exePath: string): $CancellablePromise<void> {
    return $Call.ByID(2853813257, platformKey, exePath);
}

export function SetProtocolEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3616914874, enabled);
}

export function SetStartProgramCentered(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3584189133, enabled);
}

export function SetStartTrayWithWindows(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(444643124, enabled);
}

export function SetTheme(themeID: string): $CancellablePromise<void> {
    return $Call.ByID(1553672910, themeID);
}

// Private type creation functions
const $$createType0 = $models.BackupResult.createFrom;
const $$createType1 = $models.AdminCheckResult.createFrom;
const $$createType2 = $models.PlatformSettings.createFrom;
const $$createType3 = $models.PlatformStartup.createFrom;
const $$createType4 = $models.ResolvePlatformLaunchResult.createFrom;
