// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} sourcePath
 * @returns {$CancellablePromise<void>}
 */
export function ApplyPlatformsJSONFile(sourcePath) {
    return $Call.ByID(2231300943, sourcePath);
}

/**
 * @param {string} platformKey
 * @param {boolean} everything
 * @returns {$CancellablePromise<$models.BackupResult>}
 */
export function BackupPlatform(platformKey, everything) {
    return $Call.ByID(2310227406, platformKey, everything).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<$models.AdminCheckResult>}
 */
export function CheckAdminForPlatform(platformKey) {
    return $Call.ByID(1142940076, platformKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<void>}
 */
export function ClearPlatformCache(platformKey) {
    return $Call.ByID(4269705643, platformKey);
}

/**
 * @param {string} platformKey
 * @param {string} exeFullPath
 * @returns {$CancellablePromise<void>}
 */
export function ConfirmPlatformExePath(platformKey, exeFullPath) {
    return $Call.ByID(3388066149, platformKey, exeFullPath);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetAppVersion() {
    return $Call.ByID(2763056880);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetDesktopHomeShortcutExists() {
    return $Call.ByID(1436342586);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetExitToTray() {
    return $Call.ByID(3705594180);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetLanguage() {
    return $Call.ByID(1329797675);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetMinimizeOnSwitch() {
    return $Call.ByID(2562015012);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetOfflineMode() {
    return $Call.ByID(125846475);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<string>}
 */
export function GetPlatformExeIcon(platformKey) {
    return $Call.ByID(3242817395, platformKey);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<string>}
 */
export function GetPlatformInstallFolder(platformKey) {
    return $Call.ByID(3951430321, platformKey);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<$models.PlatformSettings>}
 */
export function GetPlatformSettings(platformKey) {
    return $Call.ByID(1698365991, platformKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetProtocolEnabled() {
    return $Call.ByID(3867357470);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetStartProgramCentered() {
    return $Call.ByID(2764521137);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetStartTrayWithWindows() {
    return $Call.ByID(2723837104);
}

/**
 * @returns {$CancellablePromise<$models.PlatformStartup>}
 */
export function GetStartup() {
    return $Call.ByID(133724378).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetStatsEnabled() {
    return $Call.ByID(2625733805);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetStatsShare() {
    return $Call.ByID(1253816439);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetTheme() {
    return $Call.ByID(3289970754);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<boolean>}
 */
export function HasPlatformBackupFolders(platformKey) {
    return $Call.ByID(2360319221, platformKey);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<boolean>}
 */
export function HasPlatformCachePaths(platformKey) {
    return $Call.ByID(2913727920, platformKey);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<boolean>}
 */
export function HasShortcutMainExe(platformKey) {
    return $Call.ByID(340062970, platformKey);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<void>}
 */
export function LaunchPlatform(platformKey) {
    return $Call.ByID(1880641703, platformKey);
}

/**
 * @param {string} platformKey
 * @param {boolean} admin
 * @returns {$CancellablePromise<void>}
 */
export function LaunchPlatformAs(platformKey, admin) {
    return $Call.ByID(2773698227, platformKey, admin);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<void>}
 */
export function OpenPlatformBackupFolder(platformKey) {
    return $Call.ByID(1776189318, platformKey);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<void>}
 */
export function OpenPlatformFolder(platformKey) {
    return $Call.ByID(3725594492, platformKey);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function PickPlatformsJSON() {
    return $Call.ByID(2979264020);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<void>}
 */
export function ResetPlatformSettings(platformKey) {
    return $Call.ByID(232845660, platformKey);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<string>}
 */
export function ResolvePlatformExeFullPath(platformKey) {
    return $Call.ByID(986665928, platformKey);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<$models.ResolvePlatformLaunchResult>}
 */
export function ResolvePlatformLaunch(platformKey) {
    return $Call.ByID(176484757, platformKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * RestartAsAdmin re-execs elevated with args and exits; main should register winutil.RegisterSingletonReleaser first.
 * @param {string[]} args
 * @returns {$CancellablePromise<void>}
 */
export function RestartAsAdmin(args) {
    return $Call.ByID(2717041837, args);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RestoreDefaultPlatformsJSON() {
    return $Call.ByID(1760795478);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<$models.BackupResult>}
 */
export function RestoreLatestPlatformBackup(platformKey) {
    return $Call.ByID(2230632465, platformKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string[]} order
 * @returns {$CancellablePromise<void>}
 */
export function SaveHomeOrder(order) {
    return $Call.ByID(1124685899, order);
}

/**
 * @param {string} platformKey
 * @param {$models.PlatformSettings} s
 * @returns {$CancellablePromise<void>}
 */
export function SavePlatformSettings(platformKey, s) {
    return $Call.ByID(2552014136, platformKey, s);
}

/**
 * SetActionBarStatus is bound for the UI and other Go callers that go through services.
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function SetActionBarStatus(text) {
    return $Call.ByID(85095566, text);
}

/**
 * @param {boolean} create
 * @returns {$CancellablePromise<void>}
 */
export function SetDesktopHomeShortcut(create) {
    return $Call.ByID(3719931318, create);
}

/**
 * @param {string[]} disabled
 * @returns {$CancellablePromise<void>}
 */
export function SetDisabledPlatforms(disabled) {
    return $Call.ByID(3278316535, disabled);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetExitToTray(enabled) {
    return $Call.ByID(4055135808, enabled);
}

/**
 * @param {string} code
 * @returns {$CancellablePromise<void>}
 */
export function SetLanguage(code) {
    return $Call.ByID(1843532479, code);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetMinimizeOnSwitch(enabled) {
    return $Call.ByID(1588199976, enabled);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetOfflineMode(enabled) {
    return $Call.ByID(821998887, enabled);
}

/**
 * @param {string} platformKey
 * @param {string} exePath
 * @returns {$CancellablePromise<void>}
 */
export function SetPlatformExePath(platformKey, exePath) {
    return $Call.ByID(2853813257, platformKey, exePath);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetProtocolEnabled(enabled) {
    return $Call.ByID(3616914874, enabled);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetStartProgramCentered(enabled) {
    return $Call.ByID(3584189133, enabled);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetStartTrayWithWindows(enabled) {
    return $Call.ByID(444643124, enabled);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetStatsEnabled(enabled) {
    return $Call.ByID(3917824985, enabled);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetStatsShare(enabled) {
    return $Call.ByID(2738502547, enabled);
}

/**
 * @param {string} themeID
 * @returns {$CancellablePromise<void>}
 */
export function SetTheme(themeID) {
    return $Call.ByID(1553672910, themeID);
}

// Private type creation functions
const $$createType0 = $models.BackupResult.createFrom;
const $$createType1 = $models.AdminCheckResult.createFrom;
const $$createType2 = $models.PlatformSettings.createFrom;
const $$createType3 = $models.PlatformStartup.createFrom;
const $$createType4 = $models.ResolvePlatformLaunchResult.createFrom;
