// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ListDir(dirPath: string): $CancellablePromise<$models.FsDirEntry[]> {
    return $Call.ByID(729165017, dirPath).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListRoots(): $CancellablePromise<string[]> {
    return $Call.ByID(3372639855).then(($result: any) => {
        return $$createType2($result);
    });
}

export function StatPath(raw: string): $CancellablePromise<$models.PathStat> {
    return $Call.ByID(1999196219, raw).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FsDirEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.PathStat.createFrom;
