// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FsDirEntry {
    /**
     * Creates a new FsDirEntry instance.
     * @param {Partial<FsDirEntry>} [$$source = {}] - The source object to create the FsDirEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FsDirEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FsDirEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FsDirEntry(/** @type {Partial<FsDirEntry>} */($$parsedSource));
    }
}

export class PathStat {
    /**
     * Creates a new PathStat instance.
     * @param {Partial<PathStat>} [$$source = {}] - The source object to create the PathStat.
     */
    constructor($$source = {}) {
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathStat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PathStat}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PathStat(/** @type {Partial<PathStat>} */($$parsedSource));
    }
}

/**
 * ToastPayload is emitted to the frontend as the "toast" custom event (Wails v3).
 */
export class ToastPayload {
    /**
     * Creates a new ToastPayload instance.
     * @param {Partial<ToastPayload>} [$$source = {}] - The source object to create the ToastPayload.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("duration" in $$source)) {
            /**
             * milliseconds; 0 means use default (5000) on the frontend
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToastPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToastPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToastPayload(/** @type {Partial<ToastPayload>} */($$parsedSource));
    }
}
