// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FsDirEntry {
    "name": string;
    "path": string;
    "isDir": boolean;

    /** Creates a new FsDirEntry instance. */
    constructor($$source: Partial<FsDirEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FsDirEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FsDirEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FsDirEntry($$parsedSource as Partial<FsDirEntry>);
    }
}

export class PathStat {
    "exists": boolean;
    "isDir": boolean;

    /** Creates a new PathStat instance. */
    constructor($$source: Partial<PathStat> = {}) {
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathStat instance from a string or object.
     */
    static createFrom($$source: any = {}): PathStat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PathStat($$parsedSource as Partial<PathStat>);
    }
}
