//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../../TcNo-Acc-Switcher/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as shortcuts$0 from "../../../../../TcNo-Acc-Switcher/internal/shortcuts/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as steam$0 from "../../../../../TcNo-Acc-Switcher/internal/steam/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "shortcuts-updated": $$createType0,
        "steam-account-updated": $$createType1,
        "toast": $$createType2,
    }));
}

// Private type creation functions
const $$createType0 = shortcuts$0.ListPayload.createFrom;
const $$createType1 = steam$0.AccountPatch.createFrom;
const $$createType2 = main$0.ToastPayload.createFrom;

configure();
