// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../../TcNo-Acc-Switcher/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as shortcuts$0 from "../../../../../TcNo-Acc-Switcher/internal/shortcuts/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as steam$0 from "../../../../../TcNo-Acc-Switcher/internal/steam/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as winutil$0 from "../../../../../TcNo-Acc-Switcher/internal/winutil/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "action-bar-status": string;
            "files-dropped": string[];
            "navigate": string;
            "shortcut:render-svg-request": winutil$0.RenderSVGRequest;
            "shortcuts-updated": shortcuts$0.ListPayload;
            "steam-account-updated": steam$0.AccountPatch;
            "time": string;
            "toast": main$0.ToastPayload;
        }
    }
}
