//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../../TcNo-Acc-Switcher/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "toast": $$createType0,
    }));
}

// Private type creation functions
const $$createType0 = main$0.ToastPayload.createFrom;

configure();
