//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcNo_Acc_Switcher_Steam {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcNo_Acc_Switcher_Steam.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear backups.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear backups of forgotten accounts?.
        /// </summary>
        internal static string ClearBackups {
            get {
                return ResourceManager.GetString("ClearBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting files.
        /// </summary>
        internal static string ErrDeleteFilesHeader {
            get {
                return ResourceManager.GetString("ErrDeleteFilesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete folder because it&apos;s not empty:.
        /// </summary>
        internal static string ErrDeleteFolderNonempty {
            get {
                return ResourceManager.GetString("ErrDeleteFolderNonempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty profile image detected (0 bytes). Can&apos;t delete to redownload.
        ///
        ///Error information:.
        /// </summary>
        internal static string ErrEmptyImage {
            get {
                return ResourceManager.GetString("ErrEmptyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TcNo Account Switcher - Empty Image Error.
        /// </summary>
        internal static string ErrEmptyImageHeader {
            get {
                return ResourceManager.GetString("ErrEmptyImageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect and download Steam profile&apos;s image from Steam servers.
        ///Check your internet connection.
        ///
        ///Details:.
        /// </summary>
        internal static string ErrImageDownloadFail {
            get {
                return ResourceManager.GetString("ErrImageDownloadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error information:.
        /// </summary>
        internal static string ErrInformation {
            get {
                return ResourceManager.GetString("ErrInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start account switcher when loginusers.vdf does not exist. Verify Steam&apos;s installation and try again.
        ///If you just deleted loginusers.vdf, try starting and logging with Steam at least once..
        /// </summary>
        internal static string ErrLoginusersNonExist {
            get {
                return ResourceManager.GetString("ErrLoginusersNonExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TcNo Account Switcher - loginusers.vdf doesn&apos;t exist.
        /// </summary>
        internal static string ErrLoginusersNonExistHeader {
            get {
                return ResourceManager.GetString("ErrLoginusersNonExistHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TcNo Account Switcher - Image download error.
        /// </summary>
        internal static string ErrProfileImageDlFail {
            get {
                return ResourceManager.GetString("ErrProfileImageDlFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not recursively delete directory! Error:.
        /// </summary>
        internal static string ErrRecursivelyDelete {
            get {
                return ResourceManager.GetString("ErrRecursivelyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam location not chosen. Resetting to old value:.
        /// </summary>
        internal static string ErrSteamLocation {
            get {
                return ResourceManager.GetString("ErrSteamLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteamSettings.json failed to load properly.
        ///Old settings are saved in settings.old.json, and a new config has been loaded..
        /// </summary>
        internal static string ErrSteamSettingsLoadFail {
            get {
                return ResourceManager.GetString("ErrSteamSettingsLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TcNo Account Switcher - Load Error.
        /// </summary>
        internal static string ErrSteamSettingsLoadFailHeader {
            get {
                return ResourceManager.GetString("ErrSteamSettingsLoadFailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please submit the crashlog and more information to the Discord, or the GitHub page.
        ///Discord: https://s.tcno.co/AccSwitcherDiscord
        ///GitHub: https://github.com/TcNobo/TcNo-Acc-Switcher.
        /// </summary>
        internal static string ErrSubmitCrashlog {
            get {
                return ResourceManager.GetString("ErrSubmitCrashlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start Tray process. Try starting it yourself using &apos;TcNo Account Switcher Tray.exe&apos;.
        /// </summary>
        internal static string ErrTrayProcessStart {
            get {
                return ResourceManager.GetString("ErrTrayProcessStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TcNo Account Switcher - Tray start fail.
        /// </summary>
        internal static string ErrTrayProcessStartHead {
            get {
                return ResourceManager.GetString("ErrTrayProcessStartHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNHANDLED CRASH.
        /// </summary>
        internal static string ErrUnhandledCrash {
            get {
                return ResourceManager.GetString("ErrUnhandledCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal unhandled exception caused the program to crash. Information saved in &quot;AccSwitcher-Crashlog.txt&quot;..
        /// </summary>
        internal static string ErrUnhandledException {
            get {
                return ResourceManager.GetString("ErrUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TcNo Account Switcher Unhandled exception.
        /// </summary>
        internal static string ErrUnhandledExceptionHeader {
            get {
                return ResourceManager.GetString("ErrUnhandledExceptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to https://tcno.co/ to check for updates.
        ///
        ///Details:.
        /// </summary>
        internal static string ErrUpdateCheckFail {
            get {
                return ResourceManager.GetString("ErrUpdateCheckFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TcNo Account Switcher - Update check error.
        /// </summary>
        internal static string ErrUpdateCheckHeader {
            get {
                return ResourceManager.GetString("ErrUpdateCheckHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished updating..
        /// </summary>
        internal static string FinishedUpdating {
            get {
                return ResourceManager.GetString("FinishedUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open GitHub to see what&apos;s new?.
        /// </summary>
        internal static string GitHubWhatsNew {
            get {
                return ResourceManager.GetString("GitHubWhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program will now close. Once opened, new images will download..
        /// </summary>
        internal static string InfoReopenImageDl {
            get {
                return ResourceManager.GetString("InfoReopenImageDl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut to: {} was deleted!.
        /// </summary>
        internal static string InfoShortcutDeleted {
            get {
                return ResourceManager.GetString("InfoShortcutDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TcNo Account Switcher will start in the Windows Tray on user login/startup (The small icons on the bottom right of your Windows Start bar.).
        /// </summary>
        internal static string InfoTrayWindowsStart {
            get {
                return ResourceManager.GetString("InfoTrayWindowsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TcNo Account Switcher will no longer start with user login/startup..
        /// </summary>
        internal static string InfoTrayWindowsStartOff {
            get {
                return ResourceManager.GetString("InfoTrayWindowsStartOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are required to pick a Steam directory for this program to work. Please check you have it installed and run this program again..
        /// </summary>
        internal static string RequiredPickSteamDir {
            get {
                return ResourceManager.GetString("RequiredPickSteamDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string StatusAccountSelected {
            get {
                return ResourceManager.GetString("StatusAccountSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Checking VAC status for each account..
        /// </summary>
        internal static string StatusCheckingVac {
            get {
                return ResourceManager.GetString("StatusCheckingVac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Checking VAC status:.
        /// </summary>
        internal static string StatusCheckingVacActive {
            get {
                return ResourceManager.GetString("StatusCheckingVacActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Closing Steam.
        /// </summary>
        internal static string StatusClosingSteam {
            get {
                return ResourceManager.GetString("StatusClosingSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Collecting Steam Accounts..
        /// </summary>
        internal static string StatusCollectingAccounts {
            get {
                return ResourceManager.GetString("StatusCollectingAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Downloading profile image:.
        /// </summary>
        internal static string StatusDownloadingProfile {
            get {
                return ResourceManager.GetString("StatusDownloadingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Editing loginusers.vdf.
        /// </summary>
        internal static string StatusEditingLoginusers {
            get {
                return ResourceManager.GetString("StatusEditingLoginusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Editing Steam&apos;s Registry keys.
        /// </summary>
        internal static string StatusEditingRegistry {
            get {
                return ResourceManager.GetString("StatusEditingRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from loginusers.vdf.
        /// </summary>
        internal static string StatusFromLoginusers {
            get {
                return ResourceManager.GetString("StatusFromLoginusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Starting image download..
        /// </summary>
        internal static string StatusImageDownloadStart {
            get {
                return ResourceManager.GetString("StatusImageDownloadStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Press Login.
        /// </summary>
        internal static string StatusPressLogin {
            get {
                return ResourceManager.GetString("StatusPressLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Ready.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Removing.
        /// </summary>
        internal static string StatusRemoving {
            get {
                return ResourceManager.GetString("StatusRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Started Steam.
        /// </summary>
        internal static string StatusStartedSteam {
            get {
                return ResourceManager.GetString("StatusStartedSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TcNo Account Switcher is already running.
        /// </summary>
        internal static string SwitcherAlreadyRunning {
            get {
                return ResourceManager.GetString("SwitcherAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TcNo Account Switcher - Duplicate start.
        /// </summary>
        internal static string SwitcherAlreadyRunningHeading {
            get {
                return ResourceManager.GetString("SwitcherAlreadyRunningHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update was found.
        /// </summary>
        internal static string UpdateFound {
            get {
                return ResourceManager.GetString("UpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update was found last launch.
        /// </summary>
        internal static string UpdateLastLaunch {
            get {
                return ResourceManager.GetString("UpdateLastLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update now?.
        /// </summary>
        internal static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
