// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RenderSVGRequest is emitted to the frontend to rasterize SVG when oksvg fails.
 */
export class RenderSVGRequest {
    /**
     * Creates a new RenderSVGRequest instance.
     * @param {Partial<RenderSVGRequest>} [$$source = {}] - The source object to create the RenderSVGRequest.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("svg" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["svg"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenderSVGRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RenderSVGRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenderSVGRequest(/** @type {Partial<RenderSVGRequest>} */($$parsedSource));
    }
}
