// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RenderSVGRequest is emitted to the frontend to rasterize SVG when oksvg fails.
 */
export class RenderSVGRequest {
    "id": string;
    "svg": string;
    "size": number;

    /** Creates a new RenderSVGRequest instance. */
    constructor($$source: Partial<RenderSVGRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("svg" in $$source)) {
            this["svg"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenderSVGRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RenderSVGRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenderSVGRequest($$parsedSource as Partial<RenderSVGRequest>);
    }
}
