// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ListPayload is the Wails event payload for [UpdatedEvent].
 */
export class ListPayload {
    /**
     * Creates a new ListPayload instance.
     * @param {Partial<ListPayload>} [$$source = {}] - The source object to create the ListPayload.
     */
    constructor($$source = {}) {
        if (!("platformKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platformKey"] = "";
        }
        if (!("shortcuts" in $$source)) {
            /**
             * @member
             * @type {ShortcutDTO[]}
             */
            this["shortcuts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ListPayload}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shortcuts" in $$parsedSource) {
            $$parsedSource["shortcuts"] = $$createField1_0($$parsedSource["shortcuts"]);
        }
        return new ListPayload(/** @type {Partial<ListPayload>} */($$parsedSource));
    }
}

/**
 * ShortcutDTO is one row for the footer game shortcut UI.
 */
export class ShortcutDTO {
    /**
     * Creates a new ShortcutDTO instance.
     * @param {Partial<ShortcutDTO>} [$$source = {}] - The source object to create the ShortcutDTO.
     */
    constructor($$source = {}) {
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("iconUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["iconUrl"] = "";
        }
        if (!("pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pinned"] = false;
        }
        if (!("isPlatformExe" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPlatformExe"] = false;
        }
        if (!("isUrl" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isUrl"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShortcutDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShortcutDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShortcutDTO(/** @type {Partial<ShortcutDTO>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ShortcutDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
