// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ListPayload is the Wails event payload for [UpdatedEvent].
 */
export class ListPayload {
    "platformKey": string;
    "shortcuts": ShortcutDTO[];

    /** Creates a new ListPayload instance. */
    constructor($$source: Partial<ListPayload> = {}) {
        if (!("platformKey" in $$source)) {
            this["platformKey"] = "";
        }
        if (!("shortcuts" in $$source)) {
            this["shortcuts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): ListPayload {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shortcuts" in $$parsedSource) {
            $$parsedSource["shortcuts"] = $$createField1_0($$parsedSource["shortcuts"]);
        }
        return new ListPayload($$parsedSource as Partial<ListPayload>);
    }
}

/**
 * ShortcutDTO is one row for the footer game shortcut UI.
 */
export class ShortcutDTO {
    "fileName": string;
    "displayName": string;
    "iconUrl": string;
    "pinned": boolean;
    "isPlatformExe": boolean;
    "isUrl": boolean;

    /** Creates a new ShortcutDTO instance. */
    constructor($$source: Partial<ShortcutDTO> = {}) {
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("iconUrl" in $$source)) {
            this["iconUrl"] = "";
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }
        if (!("isPlatformExe" in $$source)) {
            this["isPlatformExe"] = false;
        }
        if (!("isUrl" in $$source)) {
            this["isUrl"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShortcutDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ShortcutDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShortcutDTO($$parsedSource as Partial<ShortcutDTO>);
    }
}

// Private type creation functions
const $$createType0 = ShortcutDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
