// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateAccountShortcut(platformKey: string, uniqueID: string, displayName: string, stateSuffix: string, stateTitle: string, accountLogin: string): $CancellablePromise<string> {
    return $Call.ByID(1934603281, platformKey, uniqueID, displayName, stateSuffix, stateTitle, accountLogin);
}

export function CreateGameAccountShortcut(platformKey: string, uniqueID: string, accountDisplayName: string, accountLogin: string, gameFileName: string): $CancellablePromise<string> {
    return $Call.ByID(564738711, platformKey, uniqueID, accountDisplayName, accountLogin, gameFileName);
}

export function CreatePlatformShortcut(platformKey: string): $CancellablePromise<string> {
    return $Call.ByID(1046256413, platformKey);
}

export function DeletePlatformShortcut(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(85680078, platformKey);
}

export function HideShortcut(platformKey: string, fileName: string): $CancellablePromise<void> {
    return $Call.ByID(3836965482, platformKey, fileName);
}

export function ImportDroppedShortcuts(platformKey: string, srcPaths: string[]): $CancellablePromise<number> {
    return $Call.ByID(3614119248, platformKey, srcPaths);
}

export function ListShortcuts(platformKey: string): $CancellablePromise<$models.ShortcutDTO[]> {
    return $Call.ByID(532352755, platformKey).then(($result: any) => {
        return $$createType1($result);
    });
}

export function OpenShortcutFolder(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(1222665178, platformKey);
}

export function PlatformShortcutExists(platformKey: string): $CancellablePromise<boolean> {
    return $Call.ByID(3762925017, platformKey);
}

export function ReportSVGRenderResult(id: string, pngBase64: string, errMsg: string): $CancellablePromise<void> {
    return $Call.ByID(166339185, id, pngBase64, errMsg);
}

export function ResolveAccountShortcutStem(platformKey: string, uniqueID: string, displayName: string, accountLogin: string): $CancellablePromise<string> {
    return $Call.ByID(2322059396, platformKey, uniqueID, displayName, accountLogin);
}

export function RunShortcut(platformKey: string, fileName: string, admin: boolean, selectedUniqueID: string): $CancellablePromise<void> {
    return $Call.ByID(994717451, platformKey, fileName, admin, selectedUniqueID);
}

export function SaveShortcutOrder(platformKey: string, pinned: string[], dropdown: string[]): $CancellablePromise<void> {
    return $Call.ByID(2498802549, platformKey, pinned, dropdown);
}

export function ScanShortcuts(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(1113514516, platformKey);
}

// Private type creation functions
const $$createType0 = $models.ShortcutDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
