// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} platformKey
 * @param {string} uniqueID
 * @param {string} displayName
 * @param {string} stateSuffix
 * @param {string} stateTitle
 * @param {string} accountLogin
 * @returns {$CancellablePromise<string>}
 */
export function CreateAccountShortcut(platformKey, uniqueID, displayName, stateSuffix, stateTitle, accountLogin) {
    return $Call.ByID(1934603281, platformKey, uniqueID, displayName, stateSuffix, stateTitle, accountLogin);
}

/**
 * @param {string} platformKey
 * @param {string} uniqueID
 * @param {string} accountDisplayName
 * @param {string} accountLogin
 * @param {string} gameFileName
 * @returns {$CancellablePromise<string>}
 */
export function CreateGameAccountShortcut(platformKey, uniqueID, accountDisplayName, accountLogin, gameFileName) {
    return $Call.ByID(564738711, platformKey, uniqueID, accountDisplayName, accountLogin, gameFileName);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<string>}
 */
export function CreatePlatformShortcut(platformKey) {
    return $Call.ByID(1046256413, platformKey);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<void>}
 */
export function DeletePlatformShortcut(platformKey) {
    return $Call.ByID(85680078, platformKey);
}

/**
 * @param {string} platformKey
 * @param {string} fileName
 * @returns {$CancellablePromise<void>}
 */
export function HideShortcut(platformKey, fileName) {
    return $Call.ByID(3836965482, platformKey, fileName);
}

/**
 * @param {string} platformKey
 * @param {string[]} srcPaths
 * @returns {$CancellablePromise<number>}
 */
export function ImportDroppedShortcuts(platformKey, srcPaths) {
    return $Call.ByID(3614119248, platformKey, srcPaths);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<$models.ShortcutDTO[]>}
 */
export function ListShortcuts(platformKey) {
    return $Call.ByID(532352755, platformKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<void>}
 */
export function OpenShortcutFolder(platformKey) {
    return $Call.ByID(1222665178, platformKey);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<boolean>}
 */
export function PlatformShortcutExists(platformKey) {
    return $Call.ByID(3762925017, platformKey);
}

/**
 * @param {string} id
 * @param {string} pngBase64
 * @param {string} errMsg
 * @returns {$CancellablePromise<void>}
 */
export function ReportSVGRenderResult(id, pngBase64, errMsg) {
    return $Call.ByID(166339185, id, pngBase64, errMsg);
}

/**
 * @param {string} platformKey
 * @param {string} uniqueID
 * @param {string} displayName
 * @param {string} accountLogin
 * @returns {$CancellablePromise<string>}
 */
export function ResolveAccountShortcutStem(platformKey, uniqueID, displayName, accountLogin) {
    return $Call.ByID(2322059396, platformKey, uniqueID, displayName, accountLogin);
}

/**
 * @param {string} platformKey
 * @param {string} fileName
 * @param {boolean} admin
 * @param {string} selectedUniqueID
 * @returns {$CancellablePromise<void>}
 */
export function RunShortcut(platformKey, fileName, admin, selectedUniqueID) {
    return $Call.ByID(994717451, platformKey, fileName, admin, selectedUniqueID);
}

/**
 * @param {string} platformKey
 * @param {string[]} pinned
 * @param {string[]} dropdown
 * @returns {$CancellablePromise<void>}
 */
export function SaveShortcutOrder(platformKey, pinned, dropdown) {
    return $Call.ByID(2498802549, platformKey, pinned, dropdown);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<void>}
 */
export function ScanShortcuts(platformKey) {
    return $Call.ByID(1113514516, platformKey);
}

// Private type creation functions
const $$createType0 = $models.ShortcutDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
