// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service exposes game shortcut operations to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateAccountShortcut writes a desktop shortcut with CLI args for this account.
 */
export function CreateAccountShortcut(platformKey: string, uniqueID: string, displayName: string, stateSuffix: string, stateTitle: string): $CancellablePromise<string> {
    return $Call.ByID(1934603281, platformKey, uniqueID, displayName, stateSuffix, stateTitle);
}

/**
 * CreatePlatformShortcut writes a desktop shortcut that opens the switcher on this platform's page.
 */
export function CreatePlatformShortcut(platformKey: string): $CancellablePromise<string> {
    return $Call.ByID(1046256413, platformKey);
}

/**
 * DeletePlatformShortcut removes the platform switcher desktop shortcut if present.
 */
export function DeletePlatformShortcut(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(85680078, platformKey);
}

/**
 * HideShortcut hides a shortcut (rename to _ignored).
 */
export function HideShortcut(platformKey: string, fileName: string): $CancellablePromise<void> {
    return $Call.ByID(3836965482, platformKey, fileName);
}

/**
 * ListShortcuts returns persisted shortcuts and icon URLs without scanning source folders.
 */
export function ListShortcuts(platformKey: string): $CancellablePromise<$models.ShortcutDTO[]> {
    return $Call.ByID(532352755, platformKey).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * OpenShortcutFolder opens LoginCache/<platform>/Shortcuts in the file manager.
 */
export function OpenShortcutFolder(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(1222665178, platformKey);
}

/**
 * PlatformShortcutExists reports whether the platform switcher desktop shortcut exists.
 */
export function PlatformShortcutExists(platformKey: string): $CancellablePromise<boolean> {
    return $Call.ByID(3762925017, platformKey);
}

/**
 * ReportSVGRenderResult completes an async SVG→PNG rasterization requested from Go (Wails canvas fallback).
 */
export function ReportSVGRenderResult(id: string, pngBase64: string, errMsg: string): $CancellablePromise<void> {
    return $Call.ByID(166339185, id, pngBase64, errMsg);
}

/**
 * RunShortcut launches a cached .lnk or .url. When selectedUniqueID is set and AlwaysSwapOnShortcut is enabled for the platform, swaps first (strict on failure).
 */
export function RunShortcut(platformKey: string, fileName: string, admin: boolean, selectedUniqueID: string): $CancellablePromise<void> {
    return $Call.ByID(994717451, platformKey, fileName, admin, selectedUniqueID);
}

/**
 * SaveShortcutOrder persists pinned vs dropdown order (filenames only).
 */
export function SaveShortcutOrder(platformKey: string, pinned: string[], dropdown: string[]): $CancellablePromise<void> {
    return $Call.ByID(2498802549, platformKey, pinned, dropdown);
}

/**
 * ScanShortcuts reconciles Start Menu / configured folders with the cache (async).
 */
export function ScanShortcuts(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(1113514516, platformKey);
}

// Private type creation functions
const $$createType0 = $models.ShortcutDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
