// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BasicService exposes generic platform account switching to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddNew clears login state and launches the platform exe.
 */
export function AddNew(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(2759945906, platformKey);
}

/**
 * ChangeAccountImage copies an image file into the profile cache for this account.
 */
export function ChangeAccountImage(platformKey: string, uniqueID: string, sourcePath: string): $CancellablePromise<void> {
    return $Call.ByID(2305033137, platformKey, uniqueID, sourcePath);
}

/**
 * ForgetAccount removes cached data for an account.
 */
export function ForgetAccount(platformKey: string, uniqueID: string): $CancellablePromise<void> {
    return $Call.ByID(1278704355, platformKey, uniqueID);
}

/**
 * GetAccountNote reads AccountNotes from platform settings for one unique id.
 */
export function GetAccountNote(platformKey: string, uniqueID: string): $CancellablePromise<string> {
    return $Call.ByID(2494848030, platformKey, uniqueID);
}

/**
 * GetAccounts returns merged ids.json + order + notes + profile image URLs.
 */
export function GetAccounts(platformKey: string): $CancellablePromise<$models.AccountDTO[]> {
    return $Call.ByID(1547846643, platformKey).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * LaunchPlatform starts the platform without switching (delegates Steam in main).
 */
export function LaunchPlatform(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(3329801989, platformKey);
}

/**
 * RenameAccount updates the display name in ids.json and renames the cached folder when possible.
 */
export function RenameAccount(platformKey: string, uniqueID: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(1761907542, platformKey, uniqueID, newName);
}

/**
 * SaveAccountOrder persists the order of unique ids for the platform.
 */
export function SaveAccountOrder(platformKey: string, order: string[]): $CancellablePromise<void> {
    return $Call.ByID(1133064777, platformKey, order);
}

/**
 * SaveCurrent saves the live session to LoginCache under the given display name.
 */
export function SaveCurrent(platformKey: string, accountName: string): $CancellablePromise<void> {
    return $Call.ByID(888679021, platformKey, accountName);
}

/**
 * SetAccountNote updates AccountNotes in platform settings JSON.
 */
export function SetAccountNote(platformKey: string, uniqueID: string, note: string): $CancellablePromise<void> {
    return $Call.ByID(3579233602, platformKey, uniqueID, note);
}

/**
 * SwapToAccount switches to a saved account (non-Steam).
 */
export function SwapToAccount(platformKey: string, uniqueID: string, extraLaunchArgs: string[]): $CancellablePromise<void> {
    return $Call.ByID(471588502, platformKey, uniqueID, extraLaunchArgs);
}

// Private type creation functions
const $$createType0 = $models.AccountDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
