// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddNew(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(2759945906, platformKey);
}

export function AddTagToAccount(platformKey: string, uniqueID: string, tagID: string): $CancellablePromise<void> {
    return $Call.ByID(1063955948, platformKey, uniqueID, tagID);
}

export function ChangeAccountImage(platformKey: string, uniqueID: string, sourcePath: string): $CancellablePromise<void> {
    return $Call.ByID(2305033137, platformKey, uniqueID, sourcePath);
}

export function CreateTagAndAddToAccount(platformKey: string, uniqueID: string, name: string): $CancellablePromise<$models.TagDefinitionDTO> {
    return $Call.ByID(2646754509, platformKey, uniqueID, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ForgetAccount(platformKey: string, uniqueID: string): $CancellablePromise<void> {
    return $Call.ByID(1278704355, platformKey, uniqueID);
}

export function GetAccountNote(platformKey: string, uniqueID: string): $CancellablePromise<string> {
    return $Call.ByID(2494848030, platformKey, uniqueID);
}

export function GetAccounts(platformKey: string): $CancellablePromise<$models.AccountDTO[]> {
    return $Call.ByID(1547846643, platformKey).then(($result: any) => {
        return $$createType2($result);
    });
}

export function LaunchPlatform(platformKey: string): $CancellablePromise<void> {
    return $Call.ByID(3329801989, platformKey);
}

export function ListTagDefinitions(platformKey: string): $CancellablePromise<$models.TagDefinitionDTO[]> {
    return $Call.ByID(234947483, platformKey).then(($result: any) => {
        return $$createType3($result);
    });
}

export function RemoveTagFromAccount(platformKey: string, uniqueID: string, tagID: string): $CancellablePromise<void> {
    return $Call.ByID(1287521298, platformKey, uniqueID, tagID);
}

export function RenameAccount(platformKey: string, uniqueID: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(1761907542, platformKey, uniqueID, newName);
}

export function SaveAccountOrder(platformKey: string, order: string[]): $CancellablePromise<void> {
    return $Call.ByID(1133064777, platformKey, order);
}

export function SaveCurrent(platformKey: string, accountName: string): $CancellablePromise<void> {
    return $Call.ByID(888679021, platformKey, accountName);
}

export function SetAccountNote(platformKey: string, uniqueID: string, note: string): $CancellablePromise<void> {
    return $Call.ByID(3579233602, platformKey, uniqueID, note);
}

export function SwapToAccount(platformKey: string, uniqueID: string, extraLaunchArgs: string[]): $CancellablePromise<void> {
    return $Call.ByID(471588502, platformKey, uniqueID, extraLaunchArgs);
}

// Private type creation functions
const $$createType0 = $models.TagDefinitionDTO.createFrom;
const $$createType1 = $models.AccountDTO.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType0);
