// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<void>}
 */
export function AddNew(platformKey) {
    return $Call.ByID(2759945906, platformKey);
}

/**
 * @param {string} platformKey
 * @param {string} uniqueID
 * @param {string} sourcePath
 * @returns {$CancellablePromise<void>}
 */
export function ChangeAccountImage(platformKey, uniqueID, sourcePath) {
    return $Call.ByID(2305033137, platformKey, uniqueID, sourcePath);
}

/**
 * @param {string} platformKey
 * @param {string} uniqueID
 * @returns {$CancellablePromise<void>}
 */
export function ForgetAccount(platformKey, uniqueID) {
    return $Call.ByID(1278704355, platformKey, uniqueID);
}

/**
 * @param {string} platformKey
 * @param {string} uniqueID
 * @returns {$CancellablePromise<string>}
 */
export function GetAccountNote(platformKey, uniqueID) {
    return $Call.ByID(2494848030, platformKey, uniqueID);
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<$models.AccountDTO[]>}
 */
export function GetAccounts(platformKey) {
    return $Call.ByID(1547846643, platformKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} platformKey
 * @returns {$CancellablePromise<void>}
 */
export function LaunchPlatform(platformKey) {
    return $Call.ByID(3329801989, platformKey);
}

/**
 * @param {string} platformKey
 * @param {string} uniqueID
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameAccount(platformKey, uniqueID, newName) {
    return $Call.ByID(1761907542, platformKey, uniqueID, newName);
}

/**
 * @param {string} platformKey
 * @param {string[]} order
 * @returns {$CancellablePromise<void>}
 */
export function SaveAccountOrder(platformKey, order) {
    return $Call.ByID(1133064777, platformKey, order);
}

/**
 * @param {string} platformKey
 * @param {string} accountName
 * @returns {$CancellablePromise<void>}
 */
export function SaveCurrent(platformKey, accountName) {
    return $Call.ByID(888679021, platformKey, accountName);
}

/**
 * @param {string} platformKey
 * @param {string} uniqueID
 * @param {string} note
 * @returns {$CancellablePromise<void>}
 */
export function SetAccountNote(platformKey, uniqueID, note) {
    return $Call.ByID(3579233602, platformKey, uniqueID, note);
}

/**
 * @param {string} platformKey
 * @param {string} uniqueID
 * @param {string[]} extraLaunchArgs
 * @returns {$CancellablePromise<void>}
 */
export function SwapToAccount(platformKey, uniqueID, extraLaunchArgs) {
    return $Call.ByID(471588502, platformKey, uniqueID, extraLaunchArgs);
}

// Private type creation functions
const $$createType0 = $models.AccountDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
