// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AccountDTO {
    /**
     * Creates a new AccountDTO instance.
     * @param {Partial<AccountDTO>} [$$source = {}] - The source object to create the AccountDTO.
     */
    constructor($$source = {}) {
        if (!("platformKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platformKey"] = "";
        }
        if (!("uniqueId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uniqueId"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("imageUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["imageUrl"] = "";
        }
        if (!("note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["note"] = "";
        }
        if (!("currentSession" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["currentSession"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountDTO(/** @type {Partial<AccountDTO>} */($$parsedSource));
    }
}
