// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AccountDTO is one row in the generic account list.
 */
export class AccountDTO {
    "platformKey": string;
    "uniqueId": string;
    "displayName": string;
    "imageUrl": string;
    "note": string;

    /** Creates a new AccountDTO instance. */
    constructor($$source: Partial<AccountDTO> = {}) {
        if (!("platformKey" in $$source)) {
            this["platformKey"] = "";
        }
        if (!("uniqueId" in $$source)) {
            this["uniqueId"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("imageUrl" in $$source)) {
            this["imageUrl"] = "";
        }
        if (!("note" in $$source)) {
            this["note"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): AccountDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountDTO($$parsedSource as Partial<AccountDTO>);
    }
}
