// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AccountDTO {
    "platformKey": string;
    "uniqueId": string;
    "displayName": string;
    "imageUrl": string;
    "note": string;
    "currentSession": boolean;
    "lastUsed": string;
    "showLastUsed": boolean;
    "tags": AccountTagDTO[];

    /** Creates a new AccountDTO instance. */
    constructor($$source: Partial<AccountDTO> = {}) {
        if (!("platformKey" in $$source)) {
            this["platformKey"] = "";
        }
        if (!("uniqueId" in $$source)) {
            this["uniqueId"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("imageUrl" in $$source)) {
            this["imageUrl"] = "";
        }
        if (!("note" in $$source)) {
            this["note"] = "";
        }
        if (!("currentSession" in $$source)) {
            this["currentSession"] = false;
        }
        if (!("lastUsed" in $$source)) {
            this["lastUsed"] = "";
        }
        if (!("showLastUsed" in $$source)) {
            this["showLastUsed"] = false;
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): AccountDTO {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField8_0($$parsedSource["tags"]);
        }
        return new AccountDTO($$parsedSource as Partial<AccountDTO>);
    }
}

/**
 * AccountTagDTO is a resolved tag on an account row (matches TagDefinitionDTO shape).
 */
export class AccountTagDTO {
    "id": string;
    "name": string;
    "color": string;

    /** Creates a new AccountTagDTO instance. */
    constructor($$source: Partial<AccountTagDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountTagDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): AccountTagDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountTagDTO($$parsedSource as Partial<AccountTagDTO>);
    }
}

/**
 * TagDefinitionDTO is one row in the global tag list for a platform.
 */
export class TagDefinitionDTO {
    "id": string;
    "name": string;
    "color": string;

    /** Creates a new TagDefinitionDTO instance. */
    constructor($$source: Partial<TagDefinitionDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TagDefinitionDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TagDefinitionDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TagDefinitionDTO($$parsedSource as Partial<TagDefinitionDTO>);
    }
}

// Private type creation functions
const $$createType0 = AccountTagDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
