// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AccountDTO is the initial snapshot and list row model.
 */
export class AccountDTO {
    "steamId64": string;
    "personaName": string;
    "accountName": string;
    "lastLogin": string;
    "offline": boolean;
    "imageUrl": string;
    "avatarPending": boolean;
    "metaPending": boolean;
    "vac": boolean;
    "ltd": boolean;
    "showSteamId": boolean;
    "showVac": boolean;
    "showLimited": boolean;
    "showLastLogin": boolean;
    "showAccUsername": boolean;
    "collectInfo": boolean;

    /**
     * SyncError is set when background profile/avatar fetch fails (shown in UI; also logged).
     */
    "syncError": string;

    /**
     * CurrentSession is true when this row is the active Steam session per loginusers.vdf
     * True when loginusers.vdf has exactly one user with MostRecent=="1" (matches that row).
     */
    "currentSession": boolean;

    /** Creates a new AccountDTO instance. */
    constructor($$source: Partial<AccountDTO> = {}) {
        if (!("steamId64" in $$source)) {
            this["steamId64"] = "";
        }
        if (!("personaName" in $$source)) {
            this["personaName"] = "";
        }
        if (!("accountName" in $$source)) {
            this["accountName"] = "";
        }
        if (!("lastLogin" in $$source)) {
            this["lastLogin"] = "";
        }
        if (!("offline" in $$source)) {
            this["offline"] = false;
        }
        if (!("imageUrl" in $$source)) {
            this["imageUrl"] = "";
        }
        if (!("avatarPending" in $$source)) {
            this["avatarPending"] = false;
        }
        if (!("metaPending" in $$source)) {
            this["metaPending"] = false;
        }
        if (!("vac" in $$source)) {
            this["vac"] = false;
        }
        if (!("ltd" in $$source)) {
            this["ltd"] = false;
        }
        if (!("showSteamId" in $$source)) {
            this["showSteamId"] = false;
        }
        if (!("showVac" in $$source)) {
            this["showVac"] = false;
        }
        if (!("showLimited" in $$source)) {
            this["showLimited"] = false;
        }
        if (!("showLastLogin" in $$source)) {
            this["showLastLogin"] = false;
        }
        if (!("showAccUsername" in $$source)) {
            this["showAccUsername"] = false;
        }
        if (!("collectInfo" in $$source)) {
            this["collectInfo"] = false;
        }
        if (!("syncError" in $$source)) {
            this["syncError"] = "";
        }
        if (!("currentSession" in $$source)) {
            this["currentSession"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): AccountDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountDTO($$parsedSource as Partial<AccountDTO>);
    }
}

/**
 * AccountPatch is emitted when background work updates one account.
 */
export class AccountPatch {
    "steamId64": string;
    "imageUrl": string;
    "vac": boolean;
    "ltd": boolean;
    "avatarPending": boolean;
    "metaPending": boolean;
    "error": string;

    /** Creates a new AccountPatch instance. */
    constructor($$source: Partial<AccountPatch> = {}) {
        if (!("steamId64" in $$source)) {
            this["steamId64"] = "";
        }
        if (!("imageUrl" in $$source)) {
            this["imageUrl"] = "";
        }
        if (!("vac" in $$source)) {
            this["vac"] = false;
        }
        if (!("ltd" in $$source)) {
            this["ltd"] = false;
        }
        if (!("avatarPending" in $$source)) {
            this["avatarPending"] = false;
        }
        if (!("metaPending" in $$source)) {
            this["metaPending"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountPatch instance from a string or object.
     */
    static createFrom($$source: any = {}): AccountPatch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountPatch($$parsedSource as Partial<AccountPatch>);
    }
}

/**
 * Settings mirrors legacy SteamSettings.json (C#) field names for compatibility where applicable.
 * Shared fields are embedded from [platform.PlatformSettings].
 */
export class Settings {
    "RunAsAdmin": boolean;
    "TrayAccNumber": number;
    "ForgetAccountEnabled": boolean;
    "ClosingMethod": string;
    "StartingMethod": string;
    "AutoStart": boolean;
    "ShowShortNotes": boolean;
    "AccountNotes": { [_ in string]?: string };
    "FolderPath": string;
    "Steam_ShowSteamID": boolean;
    "Steam_ShowVAC": boolean;
    "Steam_ShowLimited": boolean;
    "Steam_ShowLastLogin": boolean;
    "Steam_ShowAccUsername": boolean;
    "Steam_TrayAccountName": boolean;
    "Steam_ImageExpiryTime": number;
    "Steam_OverrideState": number;
    "ShortcutsJson": { [_ in string]?: string };
    "SteamWebApiKey": string;
    "StartSilent": boolean;
    "OldUi": boolean;
    "ShowSteamSwitcher": boolean;
    "CollectInfo": boolean;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("RunAsAdmin" in $$source)) {
            this["RunAsAdmin"] = false;
        }
        if (!("TrayAccNumber" in $$source)) {
            this["TrayAccNumber"] = 0;
        }
        if (!("ForgetAccountEnabled" in $$source)) {
            this["ForgetAccountEnabled"] = false;
        }
        if (!("ClosingMethod" in $$source)) {
            this["ClosingMethod"] = "";
        }
        if (!("StartingMethod" in $$source)) {
            this["StartingMethod"] = "";
        }
        if (!("AutoStart" in $$source)) {
            this["AutoStart"] = false;
        }
        if (!("ShowShortNotes" in $$source)) {
            this["ShowShortNotes"] = false;
        }
        if (!("AccountNotes" in $$source)) {
            this["AccountNotes"] = {};
        }
        if (!("FolderPath" in $$source)) {
            this["FolderPath"] = "";
        }
        if (!("Steam_ShowSteamID" in $$source)) {
            this["Steam_ShowSteamID"] = false;
        }
        if (!("Steam_ShowVAC" in $$source)) {
            this["Steam_ShowVAC"] = false;
        }
        if (!("Steam_ShowLimited" in $$source)) {
            this["Steam_ShowLimited"] = false;
        }
        if (!("Steam_ShowLastLogin" in $$source)) {
            this["Steam_ShowLastLogin"] = false;
        }
        if (!("Steam_ShowAccUsername" in $$source)) {
            this["Steam_ShowAccUsername"] = false;
        }
        if (!("Steam_TrayAccountName" in $$source)) {
            this["Steam_TrayAccountName"] = false;
        }
        if (!("Steam_ImageExpiryTime" in $$source)) {
            this["Steam_ImageExpiryTime"] = 0;
        }
        if (!("Steam_OverrideState" in $$source)) {
            this["Steam_OverrideState"] = 0;
        }
        if (!("ShortcutsJson" in $$source)) {
            this["ShortcutsJson"] = {};
        }
        if (!("SteamWebApiKey" in $$source)) {
            this["SteamWebApiKey"] = "";
        }
        if (!("StartSilent" in $$source)) {
            this["StartSilent"] = false;
        }
        if (!("OldUi" in $$source)) {
            this["OldUi"] = false;
        }
        if (!("ShowSteamSwitcher" in $$source)) {
            this["ShowSteamSwitcher"] = false;
        }
        if (!("CollectInfo" in $$source)) {
            this["CollectInfo"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField7_0 = $$createType0;
        const $$createField17_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("AccountNotes" in $$parsedSource) {
            $$parsedSource["AccountNotes"] = $$createField7_0($$parsedSource["AccountNotes"]);
        }
        if ("ShortcutsJson" in $$parsedSource) {
            $$parsedSource["ShortcutsJson"] = $$createField17_0($$parsedSource["ShortcutsJson"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * SteamIDFormats exposes common string forms for a SteamID64 decimal string.
 */
export class SteamIDFormats {
    "ID64": string;
    "ID3": string;
    "STEAMx": string;
    "ID32": string;

    /** Creates a new SteamIDFormats instance. */
    constructor($$source: Partial<SteamIDFormats> = {}) {
        if (!("ID64" in $$source)) {
            this["ID64"] = "";
        }
        if (!("ID3" in $$source)) {
            this["ID3"] = "";
        }
        if (!("STEAMx" in $$source)) {
            this["STEAMx"] = "";
        }
        if (!("ID32" in $$source)) {
            this["ID32"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamIDFormats instance from a string or object.
     */
    static createFrom($$source: any = {}): SteamIDFormats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SteamIDFormats($$parsedSource as Partial<SteamIDFormats>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
