// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "../platform/models.js";

export class AccountDTO {
    /**
     * Creates a new AccountDTO instance.
     * @param {Partial<AccountDTO>} [$$source = {}] - The source object to create the AccountDTO.
     */
    constructor($$source = {}) {
        if (!("steamId64" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["steamId64"] = "";
        }
        if (!("personaName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["personaName"] = "";
        }
        if (!("accountName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accountName"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("lastLogin" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastLogin"] = "";
        }
        if (!("offline" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["offline"] = false;
        }
        if (!("imageUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["imageUrl"] = "";
        }
        if (!("avatarPending" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["avatarPending"] = false;
        }
        if (!("metaPending" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["metaPending"] = false;
        }
        if (!("vac" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["vac"] = false;
        }
        if (!("ltd" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ltd"] = false;
        }
        if (!("showSteamId" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showSteamId"] = false;
        }
        if (!("showVac" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showVac"] = false;
        }
        if (!("showLimited" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showLimited"] = false;
        }
        if (!("showLastLogin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showLastLogin"] = false;
        }
        if (!("showAccUsername" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showAccUsername"] = false;
        }
        if (!("collectInfo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["collectInfo"] = false;
        }
        if (!("showShortNotes" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showShortNotes"] = false;
        }
        if (!("note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["note"] = "";
        }
        if (!("avatarFrameUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["avatarFrameUrl"] = "";
        }
        if (!("miniProfileHtml" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["miniProfileHtml"] = "";
        }
        if (!("showMiniProfile" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showMiniProfile"] = false;
        }
        if (!("showAvatarFrame" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showAvatarFrame"] = false;
        }
        if (!("syncError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["syncError"] = "";
        }
        if (!("currentSession" in $$source)) {
            /**
             * CurrentSession: exactly one loginusers row has MostRecent=="1" and it is this account.
             * @member
             * @type {boolean}
             */
            this["currentSession"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountDTO(/** @type {Partial<AccountDTO>} */($$parsedSource));
    }
}

export class AccountPatch {
    /**
     * Creates a new AccountPatch instance.
     * @param {Partial<AccountPatch>} [$$source = {}] - The source object to create the AccountPatch.
     */
    constructor($$source = {}) {
        if (!("steamId64" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["steamId64"] = "";
        }
        if (!("imageUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["imageUrl"] = "";
        }
        if (!("vac" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["vac"] = false;
        }
        if (!("ltd" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ltd"] = false;
        }
        if (!("avatarPending" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["avatarPending"] = false;
        }
        if (!("metaPending" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["metaPending"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["displayName"] = undefined;
        }
        if (!("avatarFrameUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["avatarFrameUrl"] = "";
        }
        if (!("miniProfileHtml" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["miniProfileHtml"] = "";
        }
        if (!("showMiniProfile" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showMiniProfile"] = false;
        }
        if (!("showAvatarFrame" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showAvatarFrame"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountPatch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountPatch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountPatch(/** @type {Partial<AccountPatch>} */($$parsedSource));
    }
}

/**
 * InstalledGameInfo is one installed Steam app from libraryfolders / appmanifest scan.
 */
export class InstalledGameInfo {
    /**
     * Creates a new InstalledGameInfo instance.
     * @param {Partial<InstalledGameInfo>} [$$source = {}] - The source object to create the InstalledGameInfo.
     */
    constructor($$source = {}) {
        if (!("appId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appId"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstalledGameInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstalledGameInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstalledGameInfo(/** @type {Partial<InstalledGameInfo>} */($$parsedSource));
    }
}

/**
 * Settings adds Steam-only fields; shared options are embedded from platform.PlatformSettings.
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("RunAsAdmin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["RunAsAdmin"] = false;
        }
        if (!("TrayAccNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["TrayAccNumber"] = 0;
        }
        if (!("ForgetAccountEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ForgetAccountEnabled"] = false;
        }
        if (!("ClosingMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ClosingMethod"] = "";
        }
        if (!("StartingMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["StartingMethod"] = "";
        }
        if (!("AutoStart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AutoStart"] = false;
        }
        if (!("ShowShortNotes" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ShowShortNotes"] = false;
        }
        if (!("AccountNotes" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["AccountNotes"] = {};
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {platform$0.GameShortcutEntry[] | undefined}
             */
            this["Shortcuts"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["AlwaysSwapOnShortcut"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["LaunchArguments"] = undefined;
        }
        if (!("FolderPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["FolderPath"] = "";
        }
        if (!("Steam_ShowSteamID" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Steam_ShowSteamID"] = false;
        }
        if (!("Steam_ShowVAC" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Steam_ShowVAC"] = false;
        }
        if (!("Steam_ShowLimited" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Steam_ShowLimited"] = false;
        }
        if (!("Steam_ShowLastLogin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Steam_ShowLastLogin"] = false;
        }
        if (!("Steam_ShowAccUsername" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Steam_ShowAccUsername"] = false;
        }
        if (!("Steam_TrayAccountName" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Steam_TrayAccountName"] = false;
        }
        if (!("Steam_ImageExpiryTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Steam_ImageExpiryTime"] = 0;
        }
        if (!("Steam_OverrideState" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Steam_OverrideState"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["ShortcutsJson"] = undefined;
        }
        if (!("SteamWebApiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SteamWebApiKey"] = "";
        }
        if (!("ShowSteamSwitcher" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ShowSteamSwitcher"] = false;
        }
        if (!("CollectInfo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["CollectInfo"] = false;
        }
        if (!("Steam_ShowMiniProfile" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Steam_ShowMiniProfile"] = false;
        }
        if (!("Steam_ShowAvatarFrame" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Steam_ShowAvatarFrame"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType2;
        const $$createField20_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("AccountNotes" in $$parsedSource) {
            $$parsedSource["AccountNotes"] = $$createField7_0($$parsedSource["AccountNotes"]);
        }
        if ("Shortcuts" in $$parsedSource) {
            $$parsedSource["Shortcuts"] = $$createField8_0($$parsedSource["Shortcuts"]);
        }
        if ("ShortcutsJson" in $$parsedSource) {
            $$parsedSource["ShortcutsJson"] = $$createField20_0($$parsedSource["ShortcutsJson"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * SteamGameDataAppIDSets is app folder names under Steam userdata and under our Backups/Steam for this account.
 */
export class SteamGameDataAppIDSets {
    /**
     * Creates a new SteamGameDataAppIDSets instance.
     * @param {Partial<SteamGameDataAppIDSets>} [$$source = {}] - The source object to create the SteamGameDataAppIDSets.
     */
    constructor($$source = {}) {
        if (!("userdataAppIds" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["userdataAppIds"] = [];
        }
        if (!("backupAppIds" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["backupAppIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamGameDataAppIDSets instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SteamGameDataAppIDSets}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("userdataAppIds" in $$parsedSource) {
            $$parsedSource["userdataAppIds"] = $$createField0_0($$parsedSource["userdataAppIds"]);
        }
        if ("backupAppIds" in $$parsedSource) {
            $$parsedSource["backupAppIds"] = $$createField1_0($$parsedSource["backupAppIds"]);
        }
        return new SteamGameDataAppIDSets(/** @type {Partial<SteamGameDataAppIDSets>} */($$parsedSource));
    }
}

/**
 * SteamIDFormats exposes common string forms for a SteamID64 decimal string.
 */
export class SteamIDFormats {
    /**
     * Creates a new SteamIDFormats instance.
     * @param {Partial<SteamIDFormats>} [$$source = {}] - The source object to create the SteamIDFormats.
     */
    constructor($$source = {}) {
        if (!("ID64" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID64"] = "";
        }
        if (!("ID3" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID3"] = "";
        }
        if (!("STEAMx" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["STEAMx"] = "";
        }
        if (!("ID32" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID32"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamIDFormats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SteamIDFormats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SteamIDFormats(/** @type {Partial<SteamIDFormats>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = platform$0.GameShortcutEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
