// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AccountDTO is the initial snapshot and list row model.
 */
export class AccountDTO {
    /**
     * Creates a new AccountDTO instance.
     * @param {Partial<AccountDTO>} [$$source = {}] - The source object to create the AccountDTO.
     */
    constructor($$source = {}) {
        if (!("steamId64" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["steamId64"] = "";
        }
        if (!("personaName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["personaName"] = "";
        }
        if (!("accountName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accountName"] = "";
        }
        if (!("lastLogin" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastLogin"] = "";
        }
        if (!("offline" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["offline"] = false;
        }
        if (!("imageUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["imageUrl"] = "";
        }
        if (!("avatarPending" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["avatarPending"] = false;
        }
        if (!("metaPending" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["metaPending"] = false;
        }
        if (!("vac" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["vac"] = false;
        }
        if (!("ltd" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ltd"] = false;
        }
        if (!("showSteamId" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showSteamId"] = false;
        }
        if (!("showVac" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showVac"] = false;
        }
        if (!("showLimited" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showLimited"] = false;
        }
        if (!("showLastLogin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showLastLogin"] = false;
        }
        if (!("showAccUsername" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showAccUsername"] = false;
        }
        if (!("collectInfo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["collectInfo"] = false;
        }
        if (!("syncError" in $$source)) {
            /**
             * SyncError is set when background profile/avatar fetch fails (shown in UI; also logged).
             * @member
             * @type {string}
             */
            this["syncError"] = "";
        }
        if (!("currentSession" in $$source)) {
            /**
             * CurrentSession is true when this row is the active Steam session per loginusers.vdf
             * (MostRecent, or highest Timestamp when MostRecent is absent/ambiguous).
             * @member
             * @type {boolean}
             */
            this["currentSession"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountDTO(/** @type {Partial<AccountDTO>} */($$parsedSource));
    }
}

/**
 * AccountPatch is emitted when background work updates one account.
 */
export class AccountPatch {
    /**
     * Creates a new AccountPatch instance.
     * @param {Partial<AccountPatch>} [$$source = {}] - The source object to create the AccountPatch.
     */
    constructor($$source = {}) {
        if (!("steamId64" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["steamId64"] = "";
        }
        if (!("imageUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["imageUrl"] = "";
        }
        if (!("vac" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["vac"] = false;
        }
        if (!("ltd" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ltd"] = false;
        }
        if (!("avatarPending" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["avatarPending"] = false;
        }
        if (!("metaPending" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["metaPending"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountPatch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountPatch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountPatch(/** @type {Partial<AccountPatch>} */($$parsedSource));
    }
}

/**
 * Settings mirrors legacy SteamSettings.json (C#) field names for compatibility where applicable.
 * Shared fields are embedded from [platform.PlatformSettings].
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("RunAsAdmin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["RunAsAdmin"] = false;
        }
        if (!("TrayAccNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["TrayAccNumber"] = 0;
        }
        if (!("ForgetAccountEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ForgetAccountEnabled"] = false;
        }
        if (!("ClosingMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ClosingMethod"] = "";
        }
        if (!("StartingMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["StartingMethod"] = "";
        }
        if (!("AutoStart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AutoStart"] = false;
        }
        if (!("ShowShortNotes" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ShowShortNotes"] = false;
        }
        if (!("AccountNotes" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["AccountNotes"] = {};
        }
        if (!("FolderPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["FolderPath"] = "";
        }
        if (!("Steam_ShowSteamID" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Steam_ShowSteamID"] = false;
        }
        if (!("Steam_ShowVAC" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Steam_ShowVAC"] = false;
        }
        if (!("Steam_ShowLimited" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Steam_ShowLimited"] = false;
        }
        if (!("Steam_ShowLastLogin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Steam_ShowLastLogin"] = false;
        }
        if (!("Steam_ShowAccUsername" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Steam_ShowAccUsername"] = false;
        }
        if (!("Steam_TrayAccountName" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Steam_TrayAccountName"] = false;
        }
        if (!("Steam_ImageExpiryTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Steam_ImageExpiryTime"] = 0;
        }
        if (!("Steam_OverrideState" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Steam_OverrideState"] = 0;
        }
        if (!("ShortcutsJson" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["ShortcutsJson"] = {};
        }
        if (!("SteamWebApiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SteamWebApiKey"] = "";
        }
        if (!("StartSilent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["StartSilent"] = false;
        }
        if (!("OldUi" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["OldUi"] = false;
        }
        if (!("ShowSteamSwitcher" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ShowSteamSwitcher"] = false;
        }
        if (!("CollectInfo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["CollectInfo"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        const $$createField17_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("AccountNotes" in $$parsedSource) {
            $$parsedSource["AccountNotes"] = $$createField7_0($$parsedSource["AccountNotes"]);
        }
        if ("ShortcutsJson" in $$parsedSource) {
            $$parsedSource["ShortcutsJson"] = $$createField17_0($$parsedSource["ShortcutsJson"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * SteamIDFormats exposes common string forms for a SteamID64 decimal string.
 */
export class SteamIDFormats {
    /**
     * Creates a new SteamIDFormats instance.
     * @param {Partial<SteamIDFormats>} [$$source = {}] - The source object to create the SteamIDFormats.
     */
    constructor($$source = {}) {
        if (!("ID64" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID64"] = "";
        }
        if (!("ID3" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID3"] = "";
        }
        if (!("STEAMx" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["STEAMx"] = "";
        }
        if (!("ID32" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID32"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamIDFormats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SteamIDFormats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SteamIDFormats(/** @type {Partial<SteamIDFormats>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
