// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BackupSteamGameData copies live userdata for this game to Backups/Steam. Returns the backup path on success.
 * @param {string} steamID64
 * @param {string} appID
 * @returns {$CancellablePromise<string>}
 */
export function BackupSteamGameData(steamID64, appID) {
    return $Call.ByID(3596677579, steamID64, appID);
}

/**
 * @param {string} steamID64
 * @param {string} sourcePath
 * @returns {$CancellablePromise<void>}
 */
export function ChangeAccountImage(steamID64, sourcePath) {
    return $Call.ByID(2396375933, steamID64, sourcePath);
}

/**
 * CopySteamGameSettingsFrom copies <steam>/userdata/{source32}/{appID} into the current session
 * account folder, auto-backing up the destination tree into Backups/Steam first (legacy C# behavior).
 * @param {string} sourceSteamID64
 * @param {string} appID
 * @returns {$CancellablePromise<void>}
 */
export function CopySteamGameSettingsFrom(sourceSteamID64, appID) {
    return $Call.ByID(1375488891, sourceSteamID64, appID);
}

/**
 * @param {string} steamID64
 * @returns {$CancellablePromise<void>}
 */
export function ForgetSteamAccount(steamID64) {
    return $Call.ByID(741072775, steamID64);
}

/**
 * @returns {$CancellablePromise<$models.InstalledGameInfo[]>}
 */
export function GetInstalledGames() {
    return $Call.ByID(1915211510).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AccountDTO[]>}
 */
export function GetSteamAccounts() {
    return $Call.ByID(800841281).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetSteamGameDataAppIDSets lists numeric subfolder names in userdata/{id32}/ and Backups/Steam/{id32}/
 * so the client can show Copy/Backup only when local game data exists, and Restore when a backup exists.
 * @param {string} steamID64
 * @returns {$CancellablePromise<$models.SteamGameDataAppIDSets>}
 */
export function GetSteamGameDataAppIDSets(steamID64) {
    return $Call.ByID(4184082038, steamID64).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} id64
 * @returns {$CancellablePromise<$models.SteamIDFormats>}
 */
export function GetSteamIDFormats(id64) {
    return $Call.ByID(829730036, id64).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function GetSteamSettings() {
    return $Call.ByID(2672197668).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function LaunchSteam() {
    return $Call.ByID(3753458866);
}

/**
 * @param {string} steamID64
 * @param {number} personaState
 * @param {string} appID
 * @returns {$CancellablePromise<void>}
 */
export function LoginAndLaunchGame(steamID64, personaState, appID) {
    return $Call.ByID(4064692418, steamID64, personaState, appID);
}

/**
 * @param {string} steamID64
 * @returns {$CancellablePromise<void>}
 */
export function OpenUserdataFolder(steamID64) {
    return $Call.ByID(769697618, steamID64);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RefreshAllSteamImages() {
    return $Call.ByID(3418679879);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RefreshVACStatus() {
    return $Call.ByID(860421344);
}

/**
 * RestoreSteamGameSettingsTo restores from Backups/Steam/{id32}/{appID} into userdata.
 * @param {string} steamID64
 * @param {string} appID
 * @returns {$CancellablePromise<void>}
 */
export function RestoreSteamGameSettingsTo(steamID64, appID) {
    return $Call.ByID(2682924661, steamID64, appID);
}

/**
 * @param {string[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function SaveSteamAccountOrder(ids) {
    return $Call.ByID(4061371237, ids);
}

/**
 * @param {$models.Settings} st
 * @returns {$CancellablePromise<void>}
 */
export function SaveSteamSettings(st) {
    return $Call.ByID(2365799185, st);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartSteamProfileRefresh() {
    return $Call.ByID(60734561);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SteamAddNew() {
    return $Call.ByID(3697816548);
}

/**
 * @param {string} steamID64
 * @param {number} personaState
 * @param {string[]} extraLaunchArgs
 * @returns {$CancellablePromise<void>}
 */
export function SwapToSteamAccount(steamID64, personaState, extraLaunchArgs) {
    return $Call.ByID(1067253876, steamID64, personaState, extraLaunchArgs);
}

// Private type creation functions
const $$createType0 = $models.InstalledGameInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.AccountDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.SteamGameDataAppIDSets.createFrom;
const $$createType5 = $models.SteamIDFormats.createFrom;
const $$createType6 = $models.Settings.createFrom;
