// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SteamService exposes Steam accounts to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BackupSteamGameData copies live userdata for this game to Backups/Steam. Returns the backup path on success.
 */
export function BackupSteamGameData(steamID64: string, appID: string): $CancellablePromise<string> {
    return $Call.ByID(3596677579, steamID64, appID);
}

/**
 * ChangeAccountImage copies a local image into the Steam profile cache for this SteamID64.
 */
export function ChangeAccountImage(steamID64: string, sourcePath: string): $CancellablePromise<void> {
    return $Call.ByID(2396375933, steamID64, sourcePath);
}

/**
 * CopySteamGameSettingsFrom copies <steam>/userdata/{source32}/{appID} into the current session
 * account folder, auto-backing up the destination tree into Backups/Steam first (legacy C# behavior).
 */
export function CopySteamGameSettingsFrom(sourceSteamID64: string, appID: string): $CancellablePromise<void> {
    return $Call.ByID(1375488891, sourceSteamID64, appID);
}

/**
 * ForgetSteamAccount removes an account row from loginusers.vdf and deletes cached avatar files.
 */
export function ForgetSteamAccount(steamID64: string): $CancellablePromise<void> {
    return $Call.ByID(741072775, steamID64);
}

/**
 * GetInstalledGames lists installed titles (from appmanifest + optional Valve app list cache).
 */
export function GetInstalledGames(): $CancellablePromise<$models.InstalledGameInfo[]> {
    return $Call.ByID(1915211510).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSteamAccounts returns the ordered account list for first paint.
 */
export function GetSteamAccounts(): $CancellablePromise<$models.AccountDTO[]> {
    return $Call.ByID(800841281).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetSteamGameDataAppIDSets lists numeric subfolder names in userdata/{id32}/ and Backups/Steam/{id32}/
 * so the client can show Copy/Backup only when local game data exists, and Restore when a backup exists.
 */
export function GetSteamGameDataAppIDSets(steamID64: string): $CancellablePromise<$models.SteamGameDataAppIDSets> {
    return $Call.ByID(4184082038, steamID64).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetSteamIDFormats exposes ID string conversions for the given SteamID64.
 */
export function GetSteamIDFormats(id64: string): $CancellablePromise<$models.SteamIDFormats> {
    return $Call.ByID(829730036, id64).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetSteamSettings returns current Steam settings.
 */
export function GetSteamSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(2672197668).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * LaunchSteam starts Steam without changing saved accounts.
 */
export function LaunchSteam(): $CancellablePromise<void> {
    return $Call.ByID(3753458866);
}

/**
 * LoginAndLaunchGame swaps to the account then launches steam://rungameid/<appID>.
 */
export function LoginAndLaunchGame(steamID64: string, personaState: number, appID: string): $CancellablePromise<void> {
    return $Call.ByID(4064692418, steamID64, personaState, appID);
}

/**
 * OpenUserdataFolder opens userdata/<accountId> for this SteamID64.
 */
export function OpenUserdataFolder(steamID64: string): $CancellablePromise<void> {
    return $Call.ByID(769697618, steamID64);
}

/**
 * RefreshAllSteamImages deletes cached avatar files for all Steam accounts and triggers a refresh.
 */
export function RefreshAllSteamImages(): $CancellablePromise<void> {
    return $Call.ByID(3418679879);
}

/**
 * RefreshVACStatus clears VAC/profile XML caches and triggers a background profile refresh.
 */
export function RefreshVACStatus(): $CancellablePromise<void> {
    return $Call.ByID(860421344);
}

/**
 * RestoreSteamGameSettingsTo restores from Backups/Steam/{id32}/{appID} into userdata.
 */
export function RestoreSteamGameSettingsTo(steamID64: string, appID: string): $CancellablePromise<void> {
    return $Call.ByID(2682924661, steamID64, appID);
}

/**
 * SaveSteamAccountOrder persists account order by SteamID64.
 */
export function SaveSteamAccountOrder(ids: string[]): $CancellablePromise<void> {
    return $Call.ByID(4061371237, ids);
}

/**
 * SaveSteamSettings writes Steam settings.
 */
export function SaveSteamSettings(st: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(2365799185, st);
}

/**
 * StartSteamProfileRefresh fetches missing avatars and ban info in the background.
 */
export function StartSteamProfileRefresh(): $CancellablePromise<void> {
    return $Call.ByID(60734561);
}

/**
 * SteamAddNew clears saved login and launches Steam for a new account sign-in.
 */
export function SteamAddNew(): $CancellablePromise<void> {
    return $Call.ByID(3697816548);
}

/**
 * SwapToSteamAccount switches to the given account (-1 uses OverrideState for persona in localconfig).
 */
export function SwapToSteamAccount(steamID64: string, personaState: number): $CancellablePromise<void> {
    return $Call.ByID(1067253876, steamID64, personaState);
}

// Private type creation functions
const $$createType0 = $models.InstalledGameInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.AccountDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.SteamGameDataAppIDSets.createFrom;
const $$createType5 = $models.SteamIDFormats.createFrom;
const $$createType6 = $models.Settings.createFrom;
