// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SteamService exposes Steam accounts to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSteamAccounts returns the ordered account list for first paint.
 * @returns {$CancellablePromise<$models.AccountDTO[]>}
 */
export function GetSteamAccounts() {
    return $Call.ByID(800841281).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetSteamIDFormats exposes ID string conversions for the given SteamID64.
 * @param {string} id64
 * @returns {$CancellablePromise<$models.SteamIDFormats>}
 */
export function GetSteamIDFormats(id64) {
    return $Call.ByID(829730036, id64).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetSteamSettings returns current Steam settings.
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function GetSteamSettings() {
    return $Call.ByID(2672197668).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RefreshAllSteamImages deletes cached avatar files for all Steam accounts and triggers a refresh.
 * @returns {$CancellablePromise<void>}
 */
export function RefreshAllSteamImages() {
    return $Call.ByID(3418679879);
}

/**
 * RefreshVACStatus clears VAC/profile XML caches and triggers a background profile refresh.
 * @returns {$CancellablePromise<void>}
 */
export function RefreshVACStatus() {
    return $Call.ByID(860421344);
}

/**
 * SaveSteamAccountOrder persists account order by SteamID64.
 * @param {string[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function SaveSteamAccountOrder(ids) {
    return $Call.ByID(4061371237, ids);
}

/**
 * SaveSteamSettings writes Steam settings.
 * @param {$models.Settings} st
 * @returns {$CancellablePromise<void>}
 */
export function SaveSteamSettings(st) {
    return $Call.ByID(2365799185, st);
}

/**
 * StartSteamProfileRefresh fetches missing avatars and ban info in the background.
 * @returns {$CancellablePromise<void>}
 */
export function StartSteamProfileRefresh() {
    return $Call.ByID(60734561);
}

// Private type creation functions
const $$createType0 = $models.AccountDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SteamIDFormats.createFrom;
const $$createType3 = $models.Settings.createFrom;
