//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace TcNo_Acc_Switcher_Globals {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Strings {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("TcNo_Acc_Switcher_Globals.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please submit the crashlog and more information to the Discord, or the GitHub page.
        ///Discord: https://s.tcno.co/AccSwitcherDiscord
        ///GitHub: https://github.com/TCNOCo/TcNo-Acc-Switcher.
        /// </summary>
        internal static string ErrSubmitCrashlog {
            get {
                return ResourceManager.GetString("ErrSubmitCrashlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNHANDLED CRASH.
        /// </summary>
        internal static string ErrUnhandledCrash {
            get {
                return ResourceManager.GetString("ErrUnhandledCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal unhandled exception caused the program to crash. Information saved in &quot;AccSwitcher-Crashlog.txt&quot;.
        ///
        ///Full path:.
        /// </summary>
        internal static string ErrUnhandledException {
            get {
                return ResourceManager.GetString("ErrUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TcNo Account Switcher Unhandled exception.
        /// </summary>
        internal static string ErrUnhandledExceptionHeader {
            get {
                return ResourceManager.GetString("ErrUnhandledExceptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Could not connect and download Steam profile&apos;s image from Steam servers.
        ///Check your internet connection.
        ///
        ///Details: .
        /// </summary>
        internal static string SteamSwitcherFuncs_PrepareProfileImages_ {
            get {
                return ResourceManager.GetString("SteamSwitcherFuncs_PrepareProfileImages_", resourceCulture);
            }
        }
    }
}
